### ISSUE TITLE
Packaging a Windows Form as Executable

### ISSUE THREAD

**Issue by adamdriscoll** [adamdriscoll/poshprotools#1]
Hey Adam/others,

This is more relating to PoshTools Pro, but I figured I should check here as there is no separate repo/issue tracker at this time.

I am having an issue packaging a windows form as an executable with PoshTools Pro. It is just a VERY basic program to test if the packaging works (checks if AD RSAT tools are installed, and combines 2 words from text boxes). When I run the .ps1 it works fine, but when I package it, it looks like it is not packaging the "Form1.designer.ps1" as the Join-path, and $MainForm.ShowDialog() at the end both error out.

If I highlight multiple files (the Form1.ps1, Form1.designer.ps1, Form1.resx), but it does not allow me to "package as executable".

See the attached image (I am unable to capture the text as text, because it pops up and away so slowly).

![image](https://cloud.githubusercontent.com/assets/1256531/26565500/6addabe6-44b1-11e7-81d6-77637fc2b2f9.png)

I should have added the following info (I did in a followup but must have forgot to hit the comment button):

Lines 30-32 (that have the errors):
. (Join-Path $PSScriptRoot 'Form1.designer.ps1')

$MainForm.ShowDialog()

Also keep in mind that I have not manually touched the code in "Form1.Designer.ps1" at all, it is all built automatically from the designer.

**Comment by adamdriscoll** [comment]
Copied from https://github.com/adamdriscoll/poshtools/issues/526

**Comment by adamdriscoll** [comment]
@nickalleyne I uploaded a new version to the Marketplace that should fix this issue. It should be available in a couple minutes.

**Comment by nickalleyne** [comment]
That seems to have fixed the issue, thanks for dealing with it so quickly.
