### ISSUE TITLE
Documentation Link for PowerShell Universal Dashboard doesn't work

### ISSUE THREAD

**Issue by 1RedOne** [adamdriscoll/poshprotools#104]
The Documentation Link here doesn't work.

http://www.poshud.com/Home#!

When one clicks Documentation, it links to this url : https://adamdriscoll.gitbooks.io/powershell-tools-documentation/content/powershell-pro-tools-documentation/universal-dashboard.html, which has since redirected.  

A more appropriate URL for this link, would be to link here instead, https://adamdriscoll.gitbooks.io/powershell-tools-documentation/content/powershell-pro-tools-documentation/about-universal-dashboard.html

**Comment by adamdriscoll** [comment]
Ack. Thanks some one else let me know about this and I never fixed it. Will get it deployed tonight.

**Comment by 1RedOne** [comment]
Cool, checked it out and it looks good today!
