### ISSUE TITLE
Getting e is not an object When adding -computername to Get-wmiobject

### ISSUE THREAD

**Issue by itadder** [adamdriscoll/poshprotools#109]
#This is the code below that is giving me issues, 

Stop-UDDashboard -Server $Dashboard
$Dashboard = Start-UDDashboard -Content { 
    New-UDDashboard -Title "Test Acme Dashboard" -Color '#FF050F7F' -Content {
        New-UdChart -Title "Disk Space by Drive" -Type Bar -AutoRefresh -Endpoint {
  Get-WmiObject -Class win32_LogicalDisk -ComputerName WSk-ACME0669 | ForEach-Object {
          [PSCustomObject]@{ DeviceId = $_.DeviceID;
                        Size = [Math]::Round($_.Size / 1GB, 2);
                        FreeSpace = [Math]::Round($_.FreeSpace / 1GB, 2); } } | Out-UDChartData -LabelProperty "DeviceID" -Dataset @(
       New-UdChartDataset -DataProperty "Size" -Label "Size" -BackgroundColor "#80962F23" -HoverBackgroundColor "#80962F23"
       New-UdChartDataset -DataProperty "FreeSpace" -Label "Free Space" -BackgroundColor "#8014558C" -HoverBackgroundColor "#8014558C"
   )
 }
        
    }
} -Port 9292

#Open Dashboard
Start-Process http://localhost:9292
#error message   ##here
https://i.imgur.com/Yh8g6kG.png
# This is a screenshot
![dashboard](https://user-images.githubusercontent.com/6600157/32333479-702223b0-bfbe-11e7-8f01-229c3123c252.png)

**Comment by adamdriscoll** [comment]
@itadder Can you enable logging via Enable-UDLogging and reproduce this? Also, can you open the developer tools in the browser (F12), refresh the page and see if the console shows an error?

**Comment by itadder** [comment]
#Enable-UDLogging
12:04:22 DashboardController Index
12:04:23 RedirectController Index - statusCode = 404, filePath = C:\Program Files\WindowsPowerShell\Modules\UniversalDashboard\1.0.273\net451\..\client/index.html
12:04:23 LicenseController GetLicenseStatus
12:04:23 DashboardController Index - Page = home
12:04:23 LicenseController GetLicense
12:04:23 ComponentController Chart - id = 2965e1e9-f3b3-4293-8e6e-d28d2695ca7c
12:04:23 DashboardColor Parse - hexOrName = #80962F23
12:04:23 DashboardColor Parse - iColorInt = -2137641181
12:04:23 DashboardColor DashboardColor - argb = -2137641181
12:04:23 DashboardColor Parse - hexOrName = #80962F23
12:04:23 DashboardColor Parse - iColorInt = -2137641181
12:04:23 DashboardColor DashboardColor - argb = -2137641181
12:04:23 DashboardColor Parse - hexOrName = #FF7B210C
12:04:23 DashboardColor Parse - iColorInt = -8707828
12:04:23 DashboardColor DashboardColor - argb = -8707828
12:04:23 DashboardColor Parse - hexOrName = #FF7B210C
12:04:23 DashboardColor Parse - iColorInt = -8707828
12:04:23 DashboardColor DashboardColor - argb = -8707828
12:04:23 ColorExtensions rgba(150, 47, 35, 0.5019608)
12:04:23 ColorExtensions rgba(123, 33, 12, 1)
12:04:23 ColorExtensions rgba(150, 47, 35, 0.5019608)
12:04:23 ColorExtensions rgba(123, 33, 12, 1)
12:04:23 DashboardColor Parse - hexOrName = #8014558C
12:04:23 DashboardColor Parse - iColorInt = -2146151028
12:04:23 DashboardColor DashboardColor - argb = -2146151028
12:04:23 DashboardColor Parse - hexOrName = #8014558C
12:04:23 DashboardColor Parse - iColorInt = -2146151028
12:04:23 DashboardColor DashboardColor - argb = -2146151028
12:04:23 DashboardColor Parse - hexOrName = #FF7B210C
12:04:23 DashboardColor Parse - iColorInt = -8707828
12:04:23 DashboardColor DashboardColor - argb = -8707828
12:04:23 DashboardColor Parse - hexOrName = #FF7B210C
12:04:23 DashboardColor Parse - iColorInt = -8707828
12:04:23 DashboardColor DashboardColor - argb = -8707828
12:04:23 ColorExtensions rgba(20, 85, 140, 0.5019608)
12:04:23 ColorExtensions rgba(123, 33, 12, 1)
12:04:23 ColorExtensions rgba(20, 85, 140, 0.5019608)
12:04:23 ColorExtensions rgba(123, 33, 12, 1)
12:04:23 DashboardColor Parse - hexOrName = #808978FF
12:04:23 DashboardColor Parse - iColorInt = -2138474241
12:04:23 DashboardColor DashboardColor - argb = -2138474241
12:04:23 DashboardColor Parse - hexOrName = #FF8978FF
12:04:23 DashboardColor Parse - iColorInt = -7767809
12:04:23 DashboardColor DashboardColor - argb = -7767809
12:04:23 DashboardColor Parse - hexOrName = #807B210C
12:04:23 DashboardColor Parse - iColorInt = -2139414260
12:04:23 DashboardColor DashboardColor - argb = -2139414260
12:04:23 DashboardColor Parse - hexOrName = #FF7B210C
12:04:23 DashboardColor Parse - iColorInt = -8707828
12:04:23 DashboardColor DashboardColor - argb = -8707828
12:04:23 ComponentController Result: {
    "labels":  "C:",
    "datasets":  [
                     {
                         "borderColor":  "rgba(123, 33, 12, 1)",
                         "data":  476.94,
                         "borderWidth":  0,
                         "hoverBorderColor":  "rgba(123, 33, 12, 1)",
                         "label":  "Size",
                         "hoverBorderWidth":  0,
                         "hoverBackgroundColor":  "rgba(150, 47, 35, 0.5019608)",
                         "yAxisId":  "",
                         "backgroundColor":  "rgba(150, 47, 35, 0.5019608)",
                         "DataProperty":  "Size",
                         "xAxisId":  ""
                     },
                     {
                         "borderColor":  "rgba(123, 33, 12, 1)",
                         "data":  385.98,
                         "borderWidth":  0,
                         "hoverBorderColor":  "rgba(123, 33, 12, 1)",
                         "label":  "Free Space",
                         "hoverBorderWidth":  0,
                         "hoverBackgroundColor":  "rgba(20, 85, 140, 0.5019608)",
                         "yAxisId":  "",
                         "backgroundColor":  "rgba(20, 85, 140, 0.5019608)",
                         "DataProperty":  "FreeSpace",
                         "xAxisId":  ""
                     }
                 ]
}
12:04:30 RedirectController Index - statusCode = 404, filePath = C:\Program Files\WindowsPowerShell\Modules\UniversalDashboard\1.0.273\net451\..\client/index.html
12:04:39 RedirectController Index - statusCode = 404, filePath = C:\Program Files\WindowsPowerShell\Modules\UniversalDashboard\1.0.273\net451\..\client/index.html
12:04:51 RedirectController Index - statusCode = 404, filePath = C:\Program Files\WindowsPowerShell\Modules\UniversalDashboard\1.0.273\net451\..\client/index.html
12:04:54 RedirectController Index - statusCode = 404, filePath = C:\Program Files\WindowsPowerShell\Modules\UniversalDashboard\1.0.273\net451\..\client/index.html
12:04:55 RedirectController Index - statusCode = 404, filePath = C:\Program Files\WindowsPowerShell\Modules\UniversalDashboard\1.0.273\net451\..\client/index.html
12:04:55 RedirectController Index - statusCode = 404, filePath = C:\Program Files\WindowsPowerShell\Modules\UniversalDashboard\1.0.273\net451\..\client/index.html
12:04:55 DashboardController Index
12:04:56 DashboardController Index - Page = home
12:04:56 LicenseController GetLicenseStatus
12:04:56 ComponentController Chart - id = 2965e1e9-f3b3-4293-8e6e-d28d2695ca7c
12:04:56 LicenseController GetLicense
12:04:56 DashboardColor Parse - hexOrName = #80962F23
12:04:56 DashboardColor Parse - iColorInt = -2137641181
12:04:56 DashboardColor DashboardColor - argb = -2137641181
12:04:56 DashboardColor Parse - hexOrName = #80962F23
12:04:56 DashboardColor Parse - iColorInt = -2137641181
12:04:56 DashboardColor DashboardColor - argb = -2137641181
12:04:56 DashboardColor Parse - hexOrName = #FF7B210C
12:04:56 DashboardColor Parse - iColorInt = -8707828
12:04:56 DashboardColor DashboardColor - argb = -8707828
12:04:56 DashboardColor Parse - hexOrName = #FF7B210C
12:04:56 DashboardColor Parse - iColorInt = -8707828
12:04:56 DashboardColor DashboardColor - argb = -8707828
12:04:56 ColorExtensions rgba(150, 47, 35, 0.5019608)
12:04:56 ColorExtensions rgba(123, 33, 12, 1)
12:04:56 ColorExtensions rgba(150, 47, 35, 0.5019608)
12:04:56 ColorExtensions rgba(123, 33, 12, 1)
12:04:56 DashboardColor Parse - hexOrName = #8014558C
12:04:56 DashboardColor Parse - iColorInt = -2146151028
12:04:56 DashboardColor DashboardColor - argb = -2146151028
12:04:56 DashboardColor Parse - hexOrName = #8014558C
12:04:56 DashboardColor Parse - iColorInt = -2146151028
12:04:56 DashboardColor DashboardColor - argb = -2146151028
12:04:56 DashboardColor Parse - hexOrName = #FF7B210C
12:04:56 DashboardColor Parse - iColorInt = -8707828
12:04:56 DashboardColor DashboardColor - argb = -8707828
12:04:56 DashboardColor Parse - hexOrName = #FF7B210C
12:04:56 DashboardColor Parse - iColorInt = -8707828
12:04:56 DashboardColor DashboardColor - argb = -8707828
12:04:56 ColorExtensions rgba(20, 85, 140, 0.5019608)
12:04:56 ColorExtensions rgba(123, 33, 12, 1)
12:04:56 ColorExtensions rgba(20, 85, 140, 0.5019608)
12:04:56 ColorExtensions rgba(123, 33, 12, 1)
12:04:56 DashboardColor Parse - hexOrName = #808978FF
12:04:56 DashboardColor Parse - iColorInt = -2138474241
12:04:56 DashboardColor DashboardColor - argb = -2138474241
12:04:56 DashboardColor Parse - hexOrName = #FF8978FF
12:04:56 DashboardColor Parse - iColorInt = -7767809
12:04:56 DashboardColor DashboardColor - argb = -7767809
12:04:56 DashboardColor Parse - hexOrName = #807B210C
12:04:56 DashboardColor Parse - iColorInt = -2139414260
12:04:56 DashboardColor DashboardColor - argb = -2139414260
12:04:56 DashboardColor Parse - hexOrName = #FF7B210C
12:04:56 DashboardColor Parse - iColorInt = -8707828
12:04:56 DashboardColor DashboardColor - argb = -8707828
12:04:56 ComponentController Result: {
    "labels":  "C:",
    "datasets":  [
                     {
                         "borderColor":  "rgba(123, 33, 12, 1)",
                         "data":  476.94,
                         "borderWidth":  0,
                         "hoverBorderColor":  "rgba(123, 33, 12, 1)",
                         "label":  "Size",
                         "hoverBorderWidth":  0,
                         "hoverBackgroundColor":  "rgba(150, 47, 35, 0.5019608)",
                         "yAxisId":  "",
                         "backgroundColor":  "rgba(150, 47, 35, 0.5019608)",
                         "DataProperty":  "Size",
                         "xAxisId":  ""
                     },
                     {
                         "borderColor":  "rgba(123, 33, 12, 1)",
                         "data":  385.98,
                         "borderWidth":  0,
                         "hoverBorderColor":  "rgba(123, 33, 12, 1)",
                         "label":  "Free Space",
                         "hoverBorderWidth":  0,
                         "hoverBackgroundColor":  "rgba(20, 85, 140, 0.5019608)",
                         "yAxisId":  "",
                         "backgroundColor":  "rgba(20, 85, 140, 0.5019608)",
                         "DataProperty":  "FreeSpace",
                         "xAxisId":  ""
                     }
                 ]
}
12:05:16 RedirectController Index - statusCode = 404, filePath = C:\Program Files\WindowsPowerShell\Modules\UniversalDashboard\1.0.273\net451\..\client/index.html

#Console in browser
TypeError: e is not an object
Stack trace:
t@http://localhost:9292/bundle.js:104:840139
buildOrUpdateElements@http://localhost:9292/bundle.js:104:842184
update/<@http://localhost:9292/bundle.js:104:834681
each@http://localhost:9292/bundle.js:34:73629
update@http://localhost:9292/bundle.js:104:834644
construct@http://localhost:9292/bundle.js:104:832057
e@http://localhost:9292/bundle.js:104:788425
_</t.prototype.renderChart@http://localhost:9292/bundle.js:48:34293
_</t.prototype.componentDidMount@http://localhost:9292/bundle.js:48:32155
commitLifeCycles@http://localhost:9292/bundle.js:48:296979
n@http://localhost:9292/bundle.js:48:301086
c@http://localhost:9292/bundle.js:48:302752
u@http://localhost:9292/bundle.js:48:303195
h@http://localhost:9292/bundle.js:48:305217
m@http://localhost:9292/bundle.js:48:304726
enqueueSetState@http://localhost:9292/bundle.js:48:285996
o.prototype.setState@http://localhost:9292/bundle.js:48:266439
value/<@http://localhost:9292/bundle.js:104:785281

**Comment by adamdriscoll** [comment]
@itadder This is an issue with returning a single data item back to the chart. It works if you have multiple items (like 2 drives) but not if there is a single item. 

I'm looking into it.

**Comment by itadder** [comment]
Ahh make sense, my PC has muptile Drives. LOL (one for my repos) and one for OS.

**Comment by adamdriscoll** [comment]
I have a fix and will get it tested and released this weekend. Thanks!

**Comment by itadder** [comment]
Thanks again.

**Comment by adamdriscoll** [comment]
Fixed in next build.

**Comment by itadder** [comment]
Thanks again
