### ISSUE TITLE
Error in compiling with form build

### ISSUE THREAD

**Issue by i3igi3yrd** [adamdriscoll/poshprotools#113]
I've been working on the same project for weeks. 

I added some code to it today and packaged as exe. When I run the exe, I get 
![image](https://user-images.githubusercontent.com/11726197/32384812-1c92273c-c08a-11e7-9aff-f27d9ae898cd.png)

Looking at the designer file code I see:
Add-Member -InputObject $MainForm -Name GroupMembershipUser -Value $GroupMembershipUser -MemberType NoteProperty
Add-Member -InputObject $MainForm -Name groupnameinput -Value $groupnameinput -MemberType NoteProperty

It's almost like it no longer seeing the "$groupnameinput -MemberType No" portion of the above code at all. Not sure what could be causing. After Getting the error, the app opens.

**Comment by adamdriscoll** [comment]
Very weird. I'll try to reproduce and if not a zipped up PSProj with the issue would be helpful. I'll let you know!

**Comment by i3igi3yrd** [comment]
Left it on work PC. Will have it to you first thing next week. Thanks

**Comment by i3igi3yrd** [comment]
Packing up the project now. What;s the best way to get it to you? 

Here's the code that seems to be getting truncated:
![image](https://user-images.githubusercontent.com/11726197/32450593-3dbbdb5e-c2da-11e7-80fd-66ac95b5bcc3.png)

**Comment by adamdriscoll** [comment]
Can you send a ZIP to adam[at]poshtools[dot]com?

**Comment by adamdriscoll** [comment]
@i3igi3yrd This has been fixed. It was a very strange string truncation issue in .NET Core but I've resolved it. A new build will be available on the VS Gallery shortly.
