### ISSUE TITLE
Does not seem to work or not installed correctly

### ISSUE THREAD

**Issue by TurboCooler** [adamdriscoll/poshprotools#12]
I purchased the license.  I received a key.  I went to help and installed the key.  I shutdown VS Studio 15 and restarted.

I was trying to use the code conversion by doing

"Convert between PowerShell and C# by simply copying the source language code and pasting it into the target source code file. "

Nothing seems to happen

Since the documentation is pretty much none existent, not sure how to continue at this point.

What can I do see if everything is installed and working?

**Comment by adamdriscoll** [comment]
Hey @TurboCooler,
Sorry you're having problems. If you installed the key and it's showing your email and expiration date, then you're good on the licensing front. When you right click in a C# or PowerShell file, you should have either Paste as C# or Paste as PowerShell. 

Some examples can be found here: https://poshtools.com/docs/posh-pro-tools/code-conversion/

Here is an overview of the code conversion feature: https://poshtools.com/docs/posh-pro-tools/code-conversion-overview/

If you have specific snippets that you are having trouble converting and do not want to post them publicly, feel free to send me an email at adam[at]poshtools.com.

**Comment by adamdriscoll** [comment]
@TurboCooler - I haven't heard back so  I'm not sure if you're still having problems. Feel free to re-open if you are.

**Comment by TurboCooler** [comment]
I now have it working.  Thanks for checking

Enzo

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
