### ISSUE TITLE
Form add control error framework

### ISSUE THREAD

**Issue by MatijaTerzic** [adamdriscoll/poshprotools#120]
When i create a new form and try to add a control it gives the following error:

Visual Studio Community 2017 / Win 10

![afbeelding](https://user-images.githubusercontent.com/7339431/32554223-5b53d8e0-c499-11e7-8578-0d0f0a7a0ff0.png)

**Comment by adamdriscoll** [comment]
@MatijaTerzic What version of the .NET Framework do you have installed? You should be able to list it in PowerShell with $PSVersionTable

**Comment by MatijaTerzic** [comment]
Problem solved. I had only "Universal Windows Platform Development" installed.
