### ISSUE TITLE
Endpoints appear to have no access to variables inside a loop. 

### ISSUE THREAD

**Issue by AmazingWizard** [adamdriscoll/poshprotools#121]
It could be that I'm going about this the wrong way, or there could be something legit broken here. 

I want to generate a New-UDChart for each item in a list of data. Here is an example of that not working: 

[https://gist.github.com/AmazingWizard/a58ead3f5bc500bbfb9f8af79d4c80cb](https://gist.github.com/AmazingWizard/a58ead3f5bc500bbfb9f8af79d4c80cb)

This returns a Null value when the chart is generated. The only thing I can come up with is that the endpoint is out of scope. I found this when building a dashboard that has a chart for each printer in my environment with its toner levels. 

Let me know if I'm just doing this wrong. 

Thanks!

**Comment by adamdriscoll** [comment]
Seems like this is a bug. Thanks for providing the reproducible script. I see the same issue. The endpoints run in an isolated runspace pool. UD tries to move the variables into the pool so they are accessible. This should work. I will look into it!

**Comment by AmazingWizard** [comment]
Excellent, I'm not crazy after all! This tool is incredible btw. I hacked something together using Agular and Firebase a year ago to get a dashboard for a coworker. This thing will easily replace that and then some.

**Comment by adamdriscoll** [comment]
Thanks!! I'm glad you dig it. Hopefully it will become more and more useful. 

Squashed the bug that was causing this. It'll be in the next build on Sunday. 

![image](https://user-images.githubusercontent.com/1256531/32585784-bd66f6d6-c4c4-11e7-9463-890b67900f12.png)

**Comment by AmazingWizard** [comment]
Awesome! Looking forward to this!
