### ISSUE TITLE
Follow up to issue #121 - Data appears jumbled on page reload

### ISSUE THREAD

**Issue by AmazingWizard** [adamdriscoll/poshprotools#134]
Follow up to https://github.com/adamdriscoll/poshprotools/issues/121

Hey there, just mentioned this in Gitter. It appears that data is coming out jumbled on page load when iterating over an array to build multiple charts. 

![datajumble](https://user-images.githubusercontent.com/7016247/32748848-75166054-c88b-11e7-871f-26ec20581ce5.gif)

Unsure if this is a logic issue in my approach to making multiple charts from an array of data, or an underlying issue with UD. 

You can use the same code provided in the original issue to replicate this effect. At times charts will initially load NULL and on reload the data will jumble. See gif above.

**Comment by adamdriscoll** [comment]
This is fixed in the next build.
