### ISSUE TITLE
Customize or Remove Footer

### ISSUE THREAD

**Issue by adamdriscoll** [adamdriscoll/poshprotools#135]

**Comment by adamdriscoll** [comment]
Implemented in next build.

**Comment by ArtisanByteCrafter** [comment]
Mind sharing how this is implemented? Can't find it in the documentation on how to remove.

**Comment by adamdriscoll** [comment]
@artvandelay440  This is busted. I just tried in 2.0.1 and the link never goes away nor do I see new links the copyright flag works but i cant hide it. I will fix this in 2.0.2
