### ISSUE TITLE
Does either poshtools or poshprotools provide code analysis?

### ISSUE THREAD

**Issue by StingyJack** [adamdriscoll/poshprotools#146]
I was trying to find something like compiler warnings or errors in .net projects or even the results of something like PS Script Analyzer.

**Comment by adamdriscoll** [comment]
Not using PS Script Analyzer. PoshTools does some basic, syntax checking but no script analyzer rules. The VS Code extension (and PS Editor Services) do use PS Script Analyzer rules.
