### ISSUE TITLE
Tools not showing up under New -> Project -> PowerShell

### ISSUE THREAD

**Issue by johnmccrae** [adamdriscoll/poshprotools#149]
Good Day, I just bought and installed PowerShell Pro Tools for VS 2017. When I go to start a new Project, the only options I have are for a module or a script. From the blog, it's clear I am missing a few project types. What did I do wrong here?

Cheers
John

**Comment by johnmccrae** [comment]
Adding to this, when I look at the installer logs now here's what I get - Missing an AdamDriscol package.



11/20/2017 10:10:34 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\10\Desktop SDK\extension.vsixmanifest'
11/20/2017 10:10:34 AM - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\10\Windows Store SDK\extension.vsixmanifest'
11/20/2017 10:10:34 AM - Skipping 'C:\Users\jmccrae\AppData\Local\Microsoft SDKs' as it doesn't exist
11/20/2017 10:10:34 AM - **The extension with ID 'PowerShellToolsPro.AdamRDriscoll.6eeb32f4-0469-4cbd-836d-eca7cb725a06' is not installed to Visual Studio Enterprise 2017.**
11/20/2017 10:10:36 AM - Microsoft.VisualStudio.ExtensionManager.CorruptInstanceException: VSIX Installer has encountered a problem. To troubleshoot, follow the steps here: https://aka.ms/pc5ifb ---> Microsoft.VisualStudio.Setup.Dependencies.DependencyGraphConstructionException: The dependent package cannot be found: Microsoft.Net.4.6.FullRedist.Threshold,version=4.6.0.0
   at Microsoft.VisualStudio.Setup.Engine.GetProductDependencyGraph(Product product, Boolean overwrite)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.IntializePackages()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetPrerequisitesInternal(IInstallableExtension extension, ICollection`1 installedPackages, ICollection`1 installablePackages, ICollection`1 unresolvedReferences)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetPrerequisites(IInstallableExtension extension, IEnumerable`1& installedPackages, IEnumerable`1& installablePackages, IEnumerable`1& unresolvedReferences)
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   --- End of inner exception stack trace ---
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)

**Comment by adamdriscoll** [comment]
@johnmccrae There are no project types for forms; only item types. If you create a script project and then add an item to that project for a Form or WPF window, you should be able to access the designers.

**Comment by johnmccrae** [comment]
Adam, thanks. I tried to completely remove/revert all versions of the
Poshtools thinking my installs were busted. Now the tools won’t install at
all and I’m getting this error:



11/20/2017 10:10:34 AM - Capping recursion at 5 directories in each
extension root due to 'default limit'.

11/20/2017 10:10:34 AM - Found
'C:\USERS\JMCCRAE\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_81B79BB3\EXTENSIONS\szxmryfl.tah\extension.vsixmanifest'

11/20/2017 10:10:34 AM - Found 'C:\PROGRAM FILES (X86)\COMMON
FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows
Kits\10\Desktop SDK\extension.vsixmanifest'

11/20/2017 10:10:34 AM - Found 'C:\PROGRAM FILES (X86)\COMMON
FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows
Kits\10\Windows Store SDK\extension.vsixmanifest'

11/20/2017 10:10:34 AM - Skipping 'C:\Users\jmccrae\AppData\Local\Microsoft
SDKs' as it doesn't exist

11/20/2017 10:10:34 AM - The extension with ID
'PowerShellToolsPro.AdamRDriscoll.6eeb32f4-0469-4cbd-836d-eca7cb725a06' is
not installed to Visual Studio Enterprise 2017.

11/20/2017 10:10:36 AM -
Microsoft.VisualStudio.ExtensionManager.CorruptInstanceException: VSIX
Installer has encountered a problem. To troubleshoot, follow the steps
here: https://aka.ms/pc5ifb --->
Microsoft.VisualStudio.Setup.Dependencies.DependencyGraphConstructionException:
The dependent package cannot be found:
Microsoft.Net.4.6.FullRedist.Threshold,version=4.6.0.0

   at Microsoft.VisualStudio.Setup.Engine.GetProductDependencyGraph(Product
product, Boolean overwrite)

   at
Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.IntializePackages()

   at
Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetPrerequisitesInternal(IInstallableExtension
extension, ICollection`1 installedPackages, ICollection`1
installablePackages, ICollection`1 unresolvedReferences)

   at
Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetPrerequisites(IInstallableExtension
extension, IEnumerable`1& installedPackages, IEnumerable`1&
installablePackages, IEnumerable`1& unresolvedReferences)











*From:* Adam Driscoll [mailto:notifications@github.com]
*Sent:* Monday, November 20, 2017 10:55 AM
*To:* adamdriscoll/poshprotools <poshprotools@noreply.github.com>
*Cc:* johnmccrae <jmccrae@chef.io>; Mention <mention@noreply.github.com>
*Subject:* Re: [adamdriscoll/poshprotools] Tools not showing up under New
-> Project -> PowerShell (#149)



@johnmccrae <https://github.com/johnmccrae> There are no project types for
forms; only item types. If you create a script project and then add an item
to that project for a Form or WPF window, you should be able to access the
designers.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/adamdriscoll/poshprotools/issues/149#issuecomment-345792235>,
or mute the thread

**Comment by adamdriscoll** [comment]
What workloads do you have installed for Visual Studio?

**Comment by johnmccrae** [comment]
I’ve been working with C# but I have a bit of most of the workloads in
there.



*From:* Adam Driscoll [mailto:notifications@github.com]
*Sent:* Monday, November 20, 2017 11:15 AM
*To:* adamdriscoll/poshprotools <poshprotools@noreply.github.com>
*Cc:* johnmccrae <jmccrae@chef.io>; Mention <mention@noreply.github.com>
*Subject:* Re: [adamdriscoll/poshprotools] Tools not showing up under New
-> Project -> PowerShell (#149)



What workloads do you have installed for Visual Studio?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/adamdriscoll/poshprotools/issues/149#issuecomment-345798269>,
or mute the thread

**Comment by johnmccrae** [comment]
Btw, “remove, wipe and reinstall everything” is an option too.



*From:* Adam Driscoll [mailto:notifications@github.com]
*Sent:* Monday, November 20, 2017 11:15 AM
*To:* adamdriscoll/poshprotools <poshprotools@noreply.github.com>
*Cc:* johnmccrae <jmccrae@chef.io>; Mention <mention@noreply.github.com>
*Subject:* Re: [adamdriscoll/poshprotools] Tools not showing up under New
-> Project -> PowerShell (#149)



What workloads do you have installed for Visual Studio?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/adamdriscoll/poshprotools/issues/149#issuecomment-345798269>,
or mute the thread

**Comment by adamdriscoll** [comment]
It might be your best bet. I've seen this reported a couple times and actually opened an issue about it with Microsoft and that's what they ended up suggesting. 

The reason I asked about workloads is because of this part of the error: 

The dependent package cannot be found:
Microsoft.Net.4.6.FullRedist.Threshold,version=4.6.0.0

But if you're working with C#, then that should be installed.

**Comment by johnmccrae** [comment]
Got it working, thanks very much!

**Comment by adamdriscoll** [comment]
Great. Thanks!
