### ISSUE TITLE
PayPal purchase not working for me.

### ISSUE THREAD

**Issue by imorrish** [adamdriscoll/poshprotools#155]
Trying to purchase POSH Pro Tools.
 Just locks up initial popup window when clicking on PayPal button, another popup window opens but stays blank.
Will try again tomorrow.

**Comment by adamdriscoll** [comment]
@imorrish Please let me know if it works tomorrow. I just tried and the PayPal page loaded.

**Comment by adamdriscoll** [comment]
If it still doesn't work I can always send you an invoice.
