### ISSUE TITLE
Support for strings in UDCounter (or similar component)

### ISSUE THREAD

**Issue by Windos** [adamdriscoll/poshprotools#156]
Is it possible to feed a string into a UDCounter, or would it be possible to get a new component for this use case?

I'm looking to get a component where I can display some arbitrary text along with one of the Font Awesome icons. Specifically I'm wanting to show the "Latest Release" for a given GitHub repo, which happens to be in the form of "v.0.1.1".

I could also see use cases for showing the date (22 November, 2017) of a release, or the username of the latest person to "star" a repo.

If you go with a new component, could I suggest something like UDString, or UDText?

**Comment by adamdriscoll** [comment]
I like the idea of a new component. Would you want it in a Material Design card or just a floating text block that you can prefix an icon too? 

There are also things like chips we could use: http://materializecss.com/chips.html

**Comment by Windos** [comment]
My hope is to have this "text" component look as close as possible to the "counter" component (my plan is to display two counters and one "text" side by side on a row.)

![poshud-text](https://user-images.githubusercontent.com/6955786/33157406-ba554f4e-d066-11e7-8f77-e5f99dda9b80.PNG)

I only just clued in on the fact that "cards" are already in there which more than satisfy my "long(er)" form text needs.

(I like those Chips, btw, and would definitely make use of them if available... build status comes to mind.)

**Comment by adamdriscoll** [comment]
So I've been futzing with just adding new parameters to New-UDCard. So you could have something like this. 

![image](https://user-images.githubusercontent.com/1256531/33354844-6dbd455c-d47a-11e7-92c6-14789899e105.png)

With some script like this:

```
 New-UDCard -Title "Test" -Text "My text`r`nNew Line" -Id "Card" -TextAlignment Center -TextSize Medium -Watermark user
```

And then if you wanted it to update on an interval or get data from the server, you could put it in a UDColumn with an endpoint 

```
New-UDColumn -Size 2 -AutoRefresh -RefreshInterval 5 -Endpoint {
 New-UDCard -Title "Test" -Text "My text`r`nNew Line" -Id "Card" -TextAlignment Center -TextSize Medium -Watermark user
}
```

How's that sound?

**Comment by Windos** [comment]
That looks perfect got my use case, Adam!

**Comment by adamdriscoll** [comment]
Great. This will be in the next build!
