### ISSUE TITLE
UDMonitor - Index was out of range. Must be non-negative and less than the size of the collection.  Parameter name: index

### ISSUE THREAD

**Issue by GavinEke** [adamdriscoll/poshprotools#160]
After running [server-performance-dashboard.ps1](https://github.com/adamdriscoll/poshprotools/blob/master/examples/universal-dashboard/server-performance-dashboard.ps1) for a couple of minutes I keep getting `Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index` in the `Network (IO Read Bytes/sec)` box and then it stops refreshing.

Troubleshooting steps:

- When I isolate this so the dashboard is only showing this box, I do not receive the error.
- I have run the `Get-Counter` command multiple times and have never received a negative number.

**Comment by adamdriscoll** [comment]
Could you please use Enable-UDLogging -Level Debug -Console and reproduce this? I am not seeing the issue on my machine.

**Comment by GavinEke** [comment]
I can't seem to reproduce this today. Which is good its not doing it, if it starts happening again I will make sure to enable the logging.

**Comment by adamdriscoll** [comment]
Great. Thanks!

**Comment by adamdriscoll** [comment]
I just ran into this. Still trying to figure out what is actually reporting that error.

**Comment by theabraxas** [comment]
I'm also hitting this error, let me know if you'd like any data from me - I was testing out your Server Performance Dashboard and the network monitor is triggering it.

**Comment by adamdriscoll** [comment]
Tracking with: https://github.com/ironmansoftware/universal-dashboard/issues/52
