### ISSUE TITLE
UDGridData - Becomes empty and stops refreshing

### ISSUE THREAD

**Issue by GavinEke** [adamdriscoll/poshprotools#161]
After running [server-performance-dashboard.ps1](https://github.com/adamdriscoll/poshprotools/blob/master/examples/universal-dashboard/server-performance-dashboard.ps1) for a couple of minutes the `Processes` box has no entries and stops refreshing.

Troubleshooting steps:

- When I isolate this so the dashboard is only showing this box, The error still occurs.
- I have also run different data to the `Get-Process` data and it happens with that too.

Eg.

```powershell
Start-UdDashboard -Content {
    New-UdDashboard -Title "Server Performance Dashboard" -Color '#FF050F7F' -Content {
        New-UdRow {
            New-UdColumn -Size 12 {
                New-UdGrid -Title "Automatic Services NOT Started" -Headers @("Name", "State", "StartMode") -Properties @("Name", "State", "StartMode") -AutoRefresh -RefreshInterval 60 -Endpoint {
                    Get-CimInstance -ClassName Win32_Service | Where-Object {($_.StartMode -eq "Auto") -and ($_.State -eq "Stopped")} | Out-UDGridData
                }
            }
        }
    }
}
```

**Comment by adamdriscoll** [comment]
Fixed in next build.

**Comment by GavinEke** [comment]
@adamdriscoll Please see above for requested examples on #166
