### ISSUE TITLE
listView Treeview ... elements not working

### ISSUE THREAD

**Issue by testlas** [adamdriscoll/poshprotools#162]
ListView elements not working - adding nodes don't work generating errors in VS like
"is either undeclared or was never assigned. | is either undeclared or was never assigned."

Treeview adding nodes doesn't work too - generating similar errors.

In Powershell ...
` $listViewGroup1.Header = 'ListViewGroup'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
The property 'Name' cannot be found on this object. Verify that the property exists and can be set.
At c:\users\test\source\repos\PowerShellProject5\PowerShellProject5\Form1.designer.ps1:442 char:1
+ $listViewGroup1.Name = 'listViewGroup1'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
The property 'Header' cannot be found on this object. Verify that the property exists and can be set.
At c:\users\test\source\repos\PowerShellProject5\PowerShellProject5\Form1.designer.ps1:443 char:1
+ $listViewGroup2.Header = 'ListViewGroup'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
The property 'Name' cannot be found on this object. Verify that the property exists and can be set.
At c:\users\test\source\repos\PowerShellProject5\PowerShellProject5\Form1.designer.ps1:444 char:1
+ $listViewGroup2.Name = 'listViewGroup2'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
The property 'Header' cannot be found on this object. Verify that the property exists and can be set.
At c:\users\test\source\repos\PowerShellProject5\PowerShellProject5\Form1.designer.ps1:445 char:1
+ $listViewGroup3.Header = 'ListViewGroup'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

**Comment by testlas** [comment]
![treeview](https://user-images.githubusercontent.com/34057638/33311859-6669fd44-d426-11e7-85e5-35680bac7bcd.jpg)

**Comment by adamdriscoll** [comment]
This will be fixed in the next build.
