### ISSUE TITLE
Picturebox and other .. with backgroundimage value errors

### ISSUE THREAD

**Issue by testlas** [adamdriscoll/poshprotools#163]
Trying to add backgroundimage propertly or from [right click]  "Choose image" generate errors.
Background images can not be set.

Errors in jpg files:

![exception-picturebox-image](https://user-images.githubusercontent.com/34057638/33311729-0942f53a-d426-11e7-9cd7-9d7e3a7ab4ec.jpg)
![picturebox-backgroundimage](https://user-images.githubusercontent.com/34057638/33311737-0db28f72-d426-11e7-94c2-91506e609d39.jpg)

There is file with icon set in one of other elements:
Form1.resx

**Comment by adamdriscoll** [comment]
Related to #111

**Comment by adamdriscoll** [comment]
This has been fixed and will be part of the next release. The release is due out in the next couple days.
