### ISSUE TITLE
StatusStrip elements are missing after some changes/save. 

### ISSUE THREAD

**Issue by testlas** [adamdriscoll/poshprotools#164]
I need to keep adding my statusstrips elements :like status label, progress bar.
After save and doing some changes and next day after opening my project statusstrips elements in design form are gone/missing.
 
Effect in VS:
![stausstrip](https://user-images.githubusercontent.com/34057638/33316529-87af9758-d434-11e7-97f1-1ff0093f0435.jpg)

There are in designer file ps1 sometimes few times but only last are visible powershell:
[System.Windows.Forms.ToolStripStatusLabel]$toolStripStatusLabel3 = $null
[System.Windows.Forms.ToolStripProgressBar]$toolStripProgressBar2 = $null
[System.Windows.Forms.ListView]$listView1 = $null
[System.Windows.Forms.ToolStripStatusLabel]$toolStripStatusLabel4 = $null
[System.Windows.Forms.ToolStripProgressBar]$toolStripProgressBar3 = $null
[System.Windows.Forms.ToolStripProgressBar]$toolStripProgressBar4 = $null

![statusstrip2](https://user-images.githubusercontent.com/34057638/33316788-7a242f44-d435-11e7-8e69-c246400a31f8.jpg)

**Comment by adamdriscoll** [comment]
This will be fixed in the next build.
