### ISSUE TITLE
Exception of type 'PowerShellToolsPro.Packager.DotNetNotInstalledException'

### ISSUE THREAD

**Issue by murrahjm** [adamdriscoll/poshprotools#171]
Attempting to use merge-script to package my winforms powershell gui on a 2012R2 server.  Not sure if this is related to #46, but I've installed the .net 4.6.2 developer pack and the issue persists.  Any guidance on what else needs to be installed?  The build works on my development machine with visual studio, but trying to get this going on my TFS build server.

**Comment by adamdriscoll** [comment]
Do you also have .NET Core installed?

**Comment by murrahjm** [comment]
I have .net core on my dev workstation but not on the build server

**Comment by adamdriscoll** [comment]
Can you try installing it on the builder server to see if that fixes the issue? It's required by the packaging stuff.

**Comment by murrahjm** [comment]
yep sure enough that did it.  Tried it by itself and got "incorrect function" error.  Installed 4.6 dev pack along side it and I'm all good.  So I guess both are needed.

**Comment by adamdriscoll** [comment]
Great. Glad that's working for you. Updated the docs to  clearly list the requirements. 

https://adamdriscoll.gitbooks.io/powershell-tools-documentation/content/powershell-pro-tools-documentation/packaging.html
