### ISSUE TITLE
Customizable Inputs

### ISSUE THREAD

**Issue by adamdriscoll** [adamdriscoll/poshprotools#174]
It would be nice to be able to create specific input forms that didnt just get generated from the param block of an Endpoint. Instead, it would be a series of cmdlets for defining different input components. I'm envisioning something like: 

```
New-UDInput -Content {
     New-UDInputComponent -Type Select -Values $ComputerNames -Mandatory -Placeholder "Select a computer" -Name ComputerName
     New-UDInputComponent -Type TextBox -Placeholder Notes -Name Notes
     New-UDInputComponent -Type RadioButton -Values $Actions -DefaultValue "Power On" -Name Action
} -Endpoint {
    param($ComputerName, $Notes, $Action) 

    if ($Action -eq "Shut Down") {
            Stop-Computer -ComputerName $ComputerName 
     }
} 
```

**Comment by adamdriscoll** [comment]
It would be much easier to support additional controls this way. We could take advantage of all kinds of things. 

http://materializecss.com/forms.html

**Comment by adamdriscoll** [comment]
Implemented in next build. Can add additional controls as people see fit.

**Comment by kort3x** [comment]
There seems to be a problem with input fields of type 'select': Again with the hyphens.
If you pick a value containg an hyphen the input action does not redirect to the dynamic URL
