### ISSUE TITLE
Frames for UD elements

### ISSUE THREAD

**Issue by kort3x** [adamdriscoll/poshprotools#176]
Frames to group monitors, grids, cards, etc.

Would be a nice enhancement for layout purposes, especially if they were collapsible.

**Comment by adamdriscoll** [comment]
Could you give me an example or what you're looking for? Material Design has the concept of collapsible collections (which could have a single item) but I have a feeling you're looking for something slightly different. 

http://materializecss.com/collapsible.html

**Comment by kort3x** [comment]
The collapsible collections seem cool although the limitation to a single item would be a bummer.

Basicly I am looking for a way to group items and to allow the dashboard user to hide these groups, e.g. the line graphs in the picture attached.

![image](https://user-images.githubusercontent.com/13918530/33516466-78db99a6-d773-11e7-8033-12e02a1f8760.png)

I hope I made myself clear, as my English is bit rusty :/

**Comment by kort3x** [comment]
As I have no idea how the magic in the background is working i just throw a question at you:
Could a collection contain a page?

**Comment by adamdriscoll** [comment]
Pages are the top level control so that probably woudnt work. I think I see where you are coming from though by hiding groups of controls. Let me see what I can do. I'll let you know when I have something to test out.

**Comment by adamdriscoll** [comment]
@kort3x Would the collapsibles in beta3 work for this? https://adamdriscoll.gitbooks.io/powershell-universal-dashboard/content/v1.3.0-beta3.html

**Comment by kort3x** [comment]
Endpoints of UDCollapsibleItems are not working

**Comment by adamdriscoll** [comment]
This is fixed in the next build - 1.3.0-beta5

**Comment by kort3x** [comment]
nice! I just tested it an endpoints are working now.
I have Couple of questions/isssues, though:
- The -active paramter of New-UDCollapsibleItem seems not to be working?
- You seem to have to click twice to expand an item for the first time after page has been loaded.
- Can I set the backgroundcolor or fontcolor of the header of a CollapsibleItem?
- Not all icons are working (e.g. hdd_o and line_chart)

**Comment by adamdriscoll** [comment]
@kort3x I open items for there:

- #237 
- #236 
- #235 
- #234

**Comment by kort3x** [comment]
OK, thanks.
This is the first repo here on Github where I particpate so frequently so I am not quite sure yet when to open an issue.
I hope I don't bother you too much with my issues/requests.

**Comment by adamdriscoll** [comment]
I appreciate the feedback and feel free to open issues even if you have questions. It helps me know what people are struggling with and having searchable issues is good for other issues as well. 

So don't worry, you're not bothering me at all!
