### ISSUE TITLE
Default selection does not get sent to server

### ISSUE THREAD

**Issue by adamdriscoll** [adamdriscoll/poshprotools#179]
Comment from #173

> small issue with "New-UDInputComponent -Type Select":
> 
> When the page is opened it looks like the first value is preselected:
> image
> ![image](https://user-images.githubusercontent.com/1256531/33560561-b26072ec-d8d5-11e7-9a2c-5e1fd8ce591d.png)
> 
> 
> but if you click submit no value is returned.

**Comment by kort3x** [comment]
thanks
