### ISSUE TITLE
Inputs for Charts

### ISSUE THREAD

**Issue by adamdriscoll** [adamdriscoll/poshprotools#181]
The chart would update based on the input

**Comment by mattmcnabb** [comment]
Thanks for posting this issue!

My initial use-case for this is to have a drop-down selection for a date interval on a line chart. For instance, to report on a particular number of occurrences per day, over a period of 7, 30, or 180 days. I'm picturing that the selector will populate a variable that's available in the scope of the chart, and that the chart will then refresh when the variable has been set.

**Comment by ServerCare** [comment]
I have a similar requirement, I was wondering what the best way about it was. (like for example a slider as often seen in stock charts to select date ranges). A drop-down like you describe would be in a similar category.

**Comment by adamdriscoll** [comment]
Check out the latest beta1 for this functionality.
