### ISSUE TITLE
How to load and use custom PS modules in poshud?

### ISSUE THREAD

**Issue by BlackCatDeployment** [adamdriscoll/poshprotools#182]
Hello,

I begin to use PoShUD, it's a very powerful tool, thanks for your job!
I'd like to load and use some custom PS modules, as PowerVRA to get VM data usage and transform them to charts by using VMware vRA API, but I cannot use PowerVRA cmdlets on PoShUD cmdlets.
The only method I found is to import PowerVRA module on each PoShUD content/endpoint.

Is there a way to load a PS module globally for using its cmdlets on every PoShUD content/endpoint?
Thanks for your help

**Comment by adamdriscoll** [comment]
The only way is to currently load them into each endpoint. This proposed solution (#38) will be coming in a future version.

**Comment by BlackCatDeployment** [comment]
Perfect! Thanks for your feedback
