### ISSUE TITLE
[New-UDLoginPage] Press "Enter" validate the login

### ISSUE THREAD

**Issue by BlackCatDeployment** [adamdriscoll/poshprotools#186]
![image](https://user-images.githubusercontent.com/12493050/33656727-403d49c6-da77-11e7-9a00-2603416eb0ad.png)

Currently, it's necessary to click on the "LOGIN" button to submit the authentication.
Is it possible to also validate it by pressing "Enter" key?

**Comment by kort3x** [comment]
Same enhancement would be nice for the submission of inputs

**Comment by adamdriscoll** [comment]
Added  #210

**Comment by adamdriscoll** [comment]
Implemented in next build.
