### ISSUE TITLE
[New-UDInputField] Display bug when a default value is set on a textbox

### ISSUE THREAD

**Issue by BlackCatDeployment** [adamdriscoll/poshprotools#187]
When page is loaded:
![image](https://user-images.githubusercontent.com/12493050/33656970-23129530-da78-11e7-8c81-24da3c66f541.png)

When I click on the text area:
![image](https://user-images.githubusercontent.com/12493050/33657045-5c0507c4-da78-11e7-937d-eaa3d64a8b3f.png)

I confirm this behavior on Chrome 62 and IE 11. Not tested on Firefox.

**Comment by adamdriscoll** [comment]
Fixed in next version.
