### ISSUE TITLE
WinForms - Font Error

### ISSUE THREAD

**Issue by testlas** [adamdriscoll/poshprotools#190]
After some manually changes in form designer.ps1 in powershell-ise  get my next error.
Loading in VS adding extra stuff and the fontsize is not changing and get error later in powershell
Two lines edited manually to set background to button of end of file are ok and no error from powershell or VS. ( $label1.Font was never changed manually only set earlier VS forms this project/files besides those lines are on begining of file).

In powershell:
`New-Object : Cannot convert argument "2", with value: "25", for "Font" to type "System.Drawing.FontStyle": "Cannot convert value "25" to type "System.Drawing.FontStyle" due to enumeration va
lues that are not valid. Specify one of the following enumeration values and try again. The possible enumeration values are "Regular;Bold;Italic;Underline;Strikeout"."
At C:\Users\test\source\repos\PowerShellProject8\PowerShellProject8\Form1.designer.ps1:38 char:17
+ ... el2.Font = (New-Object -TypeName System.Drawing.Font -ArgumentList @( ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand`

In VS no errors:
In Forms Design - the font size 11 bold.
in debuggin option - the font size and thickness is default - no errors in console.

**Comment by testlas** [comment]
Nope it's in new created project from scratch too.

$label1.Font = (New-Object -TypeName System.Drawing.Font -ArgumentList @('Microsoft Sans Serif',[System.Single]11,25,[System.Drawing.FontStyle]::Bold,[System.Drawing.GraphicsUnit]::Point,([System.Byte][System.Byte]238)))


Problem:   It's 11,25
Should Be (dot):  11.25

**Comment by adamdriscoll** [comment]
Yep. I bet it is. Just had to fix this problem for Universal Dashboard. I will take a look.

**Comment by adamdriscoll** [comment]
Could you please try this build?  
[drop.zip](https://github.com/adamdriscoll/poshprotools/files/1537380/drop.zip)

**Comment by adamdriscoll** [comment]
Could you please try this build? 
[PowerShellToolsPro.zip](https://github.com/adamdriscoll/poshprotools/files/1537383/PowerShellToolsPro.zip)

**Comment by adamdriscoll** [comment]
I released a build that fixes this. Please feel free to reopen if you still have an issue.
