### ISSUE TITLE
Static variable lost from scope when Start-UDDashboard -AutoReload is used

### ISSUE THREAD

**Issue by jeremytbrun** [adamdriscoll/poshprotools#191]
This issue can be reproduced with any of the examples provided in the PowerShell Universal Dashboard GitHub project where a static $Data variable is defined outside of the scope of a New-UD* Cmdlet AND the -AutoReload parameter is used with Start-UDDashboard.

Initially starting the dashboard works, but further changes and saves to the file results in the static $Data variable being lost from scope or something. I've taken one of the examples and added the -AutoReload parameter to it for demonstration.

1. Open the example script in a script editor and run it to start the dashboard. View the dashboard in the browser.
2. In the editor initiate a save on the script which should prompt the browser to refresh.
3. You should notice that now there is no longer data displayed in the dashboard.
[PSUniversalDashboard-DataLostExample.zip](https://github.com/adamdriscoll/poshprotools/files/1539417/PSUniversalDashboard-DataLostExample.zip)

**Comment by adamdriscoll** [comment]
This should be fixed with the new EndpointInitializationScript parameter. Check it out:

[PSUniversalDashboard-DataLostExample.zip](https://github.com/adamdriscoll/poshprotools/files/1543621/PSUniversalDashboard-DataLostExample.zip)

**Comment by jeremytbrun** [comment]
Thanks @adamdriscoll. Is the EndpointInitializationScript ran a _only single time_ when the Dashboard is created? If so, is there some alternative to making multiple dashboard elements all use the same dataset that is always refreshed? Asking for the case where I might have multiple charts based on similar data but presenting in slightly different ways and avoiding having each chart making its own query. Can I pull the data only once on a refresh schedule and then feed multiple charts with that data?

**Comment by adamdriscoll** [comment]
@jeremytbrun Yeah. This is only run once per runspace. If you wanted to periodically refresh the data without making the same query again, I would suggest using a cache. ASP.NET Core has an in-memory cache that UD could take advantage of. I made an issue to track that https://github.com/adamdriscoll/poshprotools/issues/209

Then you could create a function that either retrieved the data from the server and stored it in the cache or retrieved the data from the cache. You could have your cache invalidate after a particular amount of time to cause the refresh to happen.
