### ISSUE TITLE
[New-UDInputField] Request to make certain inputs required for submission

### ISSUE THREAD

**Issue by artvandelay440** [adamdriscoll/poshprotools#192]
Something along the lines of
````
New-UDInputField -Type 'textbox' -Name 'TempName' -Placeholder 'Temp' -Required
````

So, this box MUST be filled in for the form to submit. Essentially the equivalent of `param(Mandatory= $True)`

**Comment by artvandelay440** [comment]
I have a workaround in place that seems to be working well, if it helps anyone. Still a nice feature to have native, but I know bugs and other features are a priority. :)

````powershell
 If ($Param1 -and $Param2 -and $Param3){
                Send-MailMessage @mailparams
                New-UDInputAction -Toast "Email Sent" -Duration 7000 -ClearInput
            }
            Else {
                New-UDInputAction -Toast "* Indicates required fields. Please ensure they are filled." -Duration 7000
            }
````

**Comment by ArtisanByteCrafter** [comment]
Honestly the workaround to this issue is not that great of a burden, I'm going to go ahead and mark this one withdrawn.
