### ISSUE TITLE
[Feature Request] Add theming/branding of button elements

### ISSUE THREAD

**Issue by artvandelay440** [adamdriscoll/poshprotools#193]
It would be great to have the ability to change the ARGB value of the button elements like 'Submit' on New-UDInput dashboards. Right now, it's green only.

![capture](https://user-images.githubusercontent.com/2523522/33734853-36c519dc-db53-11e7-942f-8153f848ef25.JPG)

**Comment by ArtisanByteCrafter** [comment]
This is resolved now with themes.
