### ISSUE TITLE
Brace placement in compound statements: only K&R variants are working

### ISSUE THREAD

**Issue by ServerCare** [adamdriscoll/poshprotools#198]
In my programming style I use Allman style/BSD style brace placement (_yes I'm that old_)https://en.wikipedia.org/wiki/Indentation_style#Allman_style

This results in errors when using UniversalDashboard calls, so for now I'm forced to use K&R style for those parts, messing up my source.

**Comment by mattmcnabb** [comment]
@ServerCare This isn't really an issue with the Universal Dashboard, but rather necessity of the way PowerShell commands are parsed. The scriptblocks that contain various dashboard elements are arguments to the -Content and -Endpoint parameters. This means that they have to follow the the parameter name immediately without any other tokens (except whitespace) or the command parsing will break. You'll see the same pattern in other function-based DSLs such as Pester.

There are some ways around this:

Capture the scriptblocks in variables first, and pass those to the -Endpoint and -Content parameters:

```powershell
$SB = { <#Do some work here#>}

New-UDChart -Endpoint $SB
```

Use a backtick to escape the line returns after the parameter names:

```powershell
New-UDChart -Endpoint `
{
...
}
```

I don't recommend using the backtick approach, as it's kind of error prone and it's hard to see.

**Comment by ServerCare** [comment]
Thanks Matt, that makes sense. consider this one closed.
