### ISSUE TITLE
An Error Occurred - A counter with a negative value was detected.

### ISSUE THREAD

**Issue by pldmgg** [adamdriscoll/poshprotools#20]
I tried running the example from here: 

https://github.com/adamdriscoll/poshprotools/blob/master/examples/universal-dashboard/server-performance-dashboard.ps1

All of the charts seemd to populate and start running without issue, but then all of the sudden I got a pop-up:

An Error Occurred - A counter with a negative value was detected.

Let me know what info you need from me to diagnose.

**Comment by adamdriscoll** [comment]
@pldmgg I just experienced this was well. This is an issue with [Get-Counter](https://stackoverflow.com/questions/11583887/get-counter-negative-denominator). I will update the example dashboard.

**Comment by adamdriscoll** [comment]
Fixed the sample
