### ISSUE TITLE
Unable to get property 'DateTime' of undefined or null reference

### ISSUE THREAD

**Issue by Stephanevg** [adamdriscoll/poshprotools#211]
I was trying to make the following example code work on my Scripting server

```PowerShell
Start-UDDashboard -Content { 
    New-UDDashboard -Title "Server Performance Dashboard" -Color '#FF050F7F' -Content { 
        New-UDTable -Title "Server Information" -Headers @("Name", "CommandLine", "Status") -Endpoint {
              Get-Service | Select Name,CommandLine,Status | Out-UDTableData -Property @("Name", "CommandLine", "Status")
          }
      }
 } -Port 1001
```

I end up with the following screen:

![image](https://user-images.githubusercontent.com/6302961/33945421-4cdc5b1a-e01f-11e7-95f6-8759f13339cf.png)

I have added http://LocalHost to my intranetWebsite in the IE security settings.

Any idea what I am doing wrong?

**Comment by Cragdoo** [comment]
Getting the same error when trying your code. Manually running the `Get-Service | Select Name,CommandLine,Status` works, just not in the dashboard

**Comment by adamdriscoll** [comment]
It's a problem with the command line being null. The JavaScript code is unhappy. I'll have to fix it. If you make sure that CommandLine is an empty string rather than null, it should work. 

```
Start-UDDashboard -Content { 
    New-UDDashboard -Title "Server Performance Dashboard" -Color '#FF050F7F' -Content { 
        New-UDTable -Title "Server Information" -Headers @("Name", "CommandLine", "Status") -Endpoint {
              Get-Service | Select Name,CommandLine,Status | % {
                   if ($_.CommandLine -eq $null) { $_.CommandLine = "" }
$_
} | Out-UDTableData -Property @("Name", "CommandLine", "Status")
          }
      }
 } -Port 1001
```

**Comment by adamdriscoll** [comment]
This is fixed in the next build.
