### ISSUE TITLE
Overlap of input controls on Chart

### ISSUE THREAD

**Issue by adamdriscoll** [adamdriscoll/poshprotools#214]
https://files.gitter.im/ironmansoftware/show-off/4SC7/inputs.gif

**Comment by adamdriscoll** [comment]
@mattmcnabb - What browser were you using? I can't repro this. An example dashboard might help too. Thanks!!

**Comment by mattmcnabb** [comment]
Might have been quantum. I'll check it out in others to verify.

**Comment by mattmcnabb** [comment]
Pretty much looks the same in all browsers for me. Here's a shot of Edge, Chrome, and FF Quantum

![image](https://user-images.githubusercontent.com/6998507/34082801-41056482-e333-11e7-8f5a-a5ca01ad8db5.png)

Is it possible it's more of a resolution/DPI thing? Also, TBH this is not a huge deal to me. I'm really happy to get the chart inputs in there at all. That's a huge win. Thanks!

**Comment by mattmcnabb** [comment]
Sorry, I forgot to include an example dashboard. here's an example:

```powershell
$Dashboard = New-UDDashboard -Title "Testing input overlap" -Content {
    New-UDRow -columns {
        New-UDColumn -size 6 -Content {
            New-UDChart -Type Line -Endpoint {
                param ($TimeRange, $ToCurrency)
                
                $Data = @(
                    [PSCustomObject]@{Day = 1; Value = 33}
                    [PSCustomObject]@{Day = 2; Value = 48}
                    [PSCustomObject]@{Day = 3; Value = 27}
                    [PSCustomObject]@{Day = 4; Value = 39}
                    [PSCustomObject]@{Day = 5; Value = 55}
                    [PSCustomObject]@{Day = 6; Value = 62}
                    [PSCustomObject]@{Day = 7; Value = 88}
                )
                $Data | Out-UDChartData -LabelProperty Day -DataProperty Value
            } -FilterFields {
                New-UDInputField -Type select -Name TimeRange -Values @("1H", "1D", "1W", "1M", "1Y", "5Y") -DefaultValue "1D"
                New-UDInputField -Type select -Name ToCurrency -Values @("USD", "ETH", "LTC") -DefaultValue "USD"
            }
        }
    } 
}

Start-UDDashboard -Dashboard $Dashboard -port 8080
```

![image](https://user-images.githubusercontent.com/6998507/34225758-88b44bc2-e595-11e7-83bd-ea20e679c937.png)


The overlap only seems to occur in a sized column. If I place the chart right inside the dashboard content scriptblock, I don't see the overlap. So here's the same chart but without the row and column formatting:

```powershell
$Dashboard = New-UDDashboard -Title "Testing input overlap" -Content {
    New-UDChart -Type Line -Endpoint {
        param ($TimeRange, $ToCurrency)
                
        $Data = @(
            [PSCustomObject]@{Day = 1; Value = 33}
            [PSCustomObject]@{Day = 2; Value = 48}
            [PSCustomObject]@{Day = 3; Value = 27}
            [PSCustomObject]@{Day = 4; Value = 39}
            [PSCustomObject]@{Day = 5; Value = 55}
            [PSCustomObject]@{Day = 6; Value = 62}
            [PSCustomObject]@{Day = 7; Value = 88}
        )
        $Data | Out-UDChartData -LabelProperty Day -DataProperty Value
    } -FilterFields {
        New-UDInputField -Type select -Name TimeRange -Values @("1H", "1D", "1W", "1M", "1Y", "5Y") -DefaultValue "1D"
        New-UDInputField -Type select -Name ToCurrency -Values @("USD", "ETH", "LTC") -DefaultValue "USD"
    }
}

Start-UDDashboard -Dashboard $Dashboard -port 8080
```

![image](https://user-images.githubusercontent.com/6998507/34225830-c2231a32-e595-11e7-854a-d01481ec8247.png)

**Comment by mattmcnabb** [comment]
Personally I kind of like the look of the input selectors when they're scrunched together rather than spread across the bottom of the chart. All that really needs to happen is to expand the chart card's bottom downward to encapsulate the input control. Not sure how that would be achieved, but again, no biggie from my perspective.

**Comment by adamdriscoll** [comment]
This is fix in the next build. Controls will stack horizontally and won't overlap.

**Comment by adamdriscoll** [comment]
1.3.0-beta5
