### ISSUE TITLE
Themes 

### ISSUE THREAD

**Issue by adamdriscoll** [adamdriscoll/poshprotools#216]
I would like to provide a way to implement a theme. 

## The general idea

Provide a general structure for the color options for a dashboard.  

## The goal of theming would be the following

- Provide a single place to configure colors for components within a dashboard
- Provide a mechanism to share themes between users
- Establish some basic, built-in themes to provide users with different 

## Some rules for themes

- Existing color configurations will still function 
- Color configurations on individual components will override theme colors, much like CSS. 
- Provide the ability to inherit a theme so you only need to customize the colors you see fit and take advantage of the parent theme's colors 

### Option 1 

Provide a documented PSD1 format for themes. Benefits would be that the themes are easily updated. There aren't any cmdlets involved so updates to the client would be easy without having to update the cmdlets for themes. The theme could then be run through a Test-UDTheme cmdlet to validate the theme syntax. 

I would imagine something like this. 

```
@{
      ParentTheme = ".\AzureGrey.psd1"
      UDCard = @{
           BackgroundColor = "#111111"
           FontColor = "#111111"
           LinkColor = "#111111"
      }
      UDChart = @{
           BackgroundColor = "#111111"
           FontColor = "#111111"
           LinkColor = "#111111"
           BarChartColors = @{
                   BackgroundColor = @("#123123", "#123131", "#1231231")
                   HoveColor = @("#123123", "#123131", "#1231231")
           }
      }
}
```

### Option 2

Provide a series of theming cmdlets. These would enforce themes based on the parameters of the cmdlets. The upside here is the discoverablity of the cmdlets. The downside is a huge explosion in cmdlets for the module. This could make it potentially hard to find the important component cmdlets.  Using a New-UDThemeX format might make that easier. 

```
 New-UDTheme -Card (New-UDCardTheme -BackgroundColor "#11111") -ParentTheme ".\AzureGrey.psd1" -Chart (New-UDChartTheme -BackgroundColor "11111")
```

### Options 3

A blend of both option 1 and 2. Instead of including the theming cmdlets in UniversalDasbhoard, I can create a separate module for themeing. UniversalDashboard.Theme or something. This has the cmdlets. UniversalDashboard proper accepts and validates Hashtables and PSD1s generated by UniversalDashboard.Theme. Users who want to create themes can use the theme module and users don't actually need the theme module to support them.

This would likely require versioning for themes. It would also require releasing two modules. 

I'm not 100% sold on any option but would love to hear feedback.

**Comment by mattmcnabb** [comment]
I like option 1. It fits in with regular design principles.

Not sure I like the idea of cmdlets for this - it would clutter the module, or create the need for a new module, and the commands themselves would be needlessly long. I'm sure each command would end up with a splatted hashtable, which in essence would be the same thing as the data file, right?

The only other design decision would probably be how to apply it to elements or to a dashboard. Would there just be parameter to New-UDDashboard for this? If this is the case, maybe there could be a parameter for each element as well? That way we could apply partial themes or apply different themes to sets of charts, etc.

**Comment by artvandelay440** [comment]
Gonna go with design 1 here. I strongly prefer JSON or other structured datatypes for these kind of things. This is very similar to how VSCode approaches settings/theming elements.

Would this be a breaking change if we already define colors in a central spot and apply them via splatting?

For example:
````powershell
$Colors = @{
    BackgroundColor = "#F7F7F7" # element background
    FontColor       = "#3E3E3E"
}

$NavColors = @{
    BackgroundColor = "#F0F0F0" # general dashboard background
    FontColor       = "#F9F9F9" # element font color
    NavBarColor     = "#3E3E3E" # nab bar background
    NavBarFontColor = "#F9F9F9"
}
````

New-UDDashboard @NavColors
New-UDCard @colors 

Would this theme style be broken after update?

**Comment by adamdriscoll** [comment]
Thanks for the feedback guys. 

@mattmcnabb Your question about how to apply the themes. I was thinking about doing at the root dashboard to start. The color options would still exist for individual controls but not necessarily a theme for a set of controls. It might get hairy but I'm willing to discuss that. 

@artvandelay440 I think that colors for specific controls would override anything in the theme. This would ensure that you could change the color of components dynamically and it wouldn't break existing color schemes.

**Comment by kort3x** [comment]
+1 for Option 1

**Comment by mattmcnabb** [comment]
It would also be really interesting to see a theme selector capability. Not sure how it would be implemented exactly, but maybe we could supply two themes (light and dark), and there could be a toggle to switch between the two.

**Comment by adamdriscoll** [comment]
The first implementation of this is complete and will be in 1.4.0. I've included parent\child theme concept and built the framework to have client-switchable themes.
