### ISSUE TITLE
Example request

### ISSUE THREAD

**Issue by ServerCare** [adamdriscoll/poshprotools#226]
I'm trying to use a . sourced function to fill my chart, but so far all I get is a warning that my function doesn't seem te be recognized. 

This is what I'm doing:

New-UdChart -Title "Gas Usage in Liters" -Type bar -AutoRefresh -RefreshInterval 30 -Endpoint {  
              _Get-GasData_ | Out-UDChartData -LabelProperty "Time" -Dataset @(...

Where Get-Gasdata is my function. If I export that data to a variable and use that it works. What am I doing wrong?

**Comment by kort3x** [comment]
I have not used it myself yet but there is an EndpointInitializationScript parameter in the 1.3.0-beta

> You can import modules, define variables and even functions.
> 
> https://adamdriscoll.gitbooks.io/powershell-universal-dashboard/content/v130-beta1.html

**Comment by mattmcnabb** [comment]
I've been using it, and it works well. So well, that I'm looking at moving all of the endpoint code out of the dashboards into a custom module just to attempt to separate the content from the layout as much as possible.

One thing I've seen is that I can't seem to use any variables from the script scope in the scriptblock passed to this parameter. So if the module you're using is not in the PSModulePath, you may have to use the absolute path to the module folder to import it:

```powershell
Import-Module "C:\Folder\Module"
```

If anyone knows a workaround for this, I'd be very appreciative ;)

**Comment by ServerCare** [comment]
attempting to install the beta, but i get:


PS C:\WINDOWS\system32> Start-UDDashboard -Port 10000 -UpdateToken 1234
Start-UDDashboard : Unable to load DLL 'libuv': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
At line:1 char:1
+ Start-UDDashboard -Port 10000 -UpdateToken 1234
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-UDDashboard], DllNotFoundException
    + FullyQualifiedErrorId : System.DllNotFoundException,PowerShellProTools.UniversalDashboard.Cmdlets.StartDashboardCommand

**Comment by adamdriscoll** [comment]
@ServerCare This should be fixed in the latest. Can you give it another shot?

**Comment by adamdriscoll** [comment]
I'm going to close this issue as I believe it to be fixed. If you find out otherwise, please let me know.

**Comment by DanielSSilva** [comment]
I don't know if it's the right place to post this, but the error is the same (although it's a different OS). I have this error on both RPi3 and my linux machine. From RPi:
```
PS /home/pi/Documents/Dashboard> ./test.ps1                                          
Start-UDDashboard : /usr/local/share/powershell/Modules/UniversalDashboard/1.6.1/netstandard2.0/runtimes/linux-arm/native/libuv.so
At /home/pi/Documents/Dashboard/test.ps1:8 char:1
+ Start-UDDashboard -Dashboard $Dashboard -Port 10000 -AutoReload
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Start-UDDashboard], DllNotFoundException
+ FullyQualifiedErrorId : System.DllNotFoundException,PowerShellProTools.UniversalDashboard.Cmdlets.StartDashboardCommand
```
I thought it could be because of my PSVersion (was on 6.1) but downgraded and the error was the same
