### ISSUE TITLE
HTTPS Example

### ISSUE THREAD

**Issue by Chirishman** [adamdriscoll/poshprotools#229]
Couldn't find a documented example for using https. You should enhance your documentation to include (and possibly prefer) http login. Especially since you are now supporting login pages. I wouldn't want to be regularly logging into something with my google account, etc over HTTP.

`Start-UDDashboard -Dashboard $Dashboard -Port 8080 -Name 'TestDashboard' -Certificate (gci Cert:\LocalMachine\My | ?{$_.Subject -eq 'CN=localhost'})`

**Comment by Chirishman** [comment]
adamdriscoll/universal-dashboard-documentation#1

**Comment by adamdriscoll** [comment]
This is now on GitBook: https://github.com/ironmansoftware/universal-dashboard/issues/30
