### ISSUE TITLE
Disallow Starting of Dashboard when Login is used and server type is HTTP

### ISSUE THREAD

**Issue by Chirishman** [adamdriscoll/poshprotools#230]
You should use a ParameterSet to prevent -LoginPage from being used without setting -Certificate or -CertificateFile to improve security and prevent the leakage of everyone's Google and Microsoft credentials.

**Comment by adamdriscoll** [comment]
This is a very good point. What I'm going to do is enforce the use of HTTPS when using login pages. I want to still provide a way to test out login pages without the use of HTTPS so will add a switch parameter to override this behavior for development machines. This will write a warning about the security implications of using the parameter.

**Comment by Chirishman** [comment]
Maybe use parameter sets but use a [hidden](https://blogs.technet.microsoft.com/heyscriptingguy/2014/12/03/powertip-use-powershell-to-hide-parameter-from-intellisense/) but documented switch parameter which is part of the HTTP set to override?

**Comment by adamdriscoll** [comment]
I don't think I'll make it hidden. I want people to be able to try out a login page before having to create a cert but you will have to specify. 

This is implemented in the next version.

**Comment by Chirishman** [comment]
Something seems broken, I'm getting a terminating error when supplying a value to the -certificate parameter unless I also set the -AllowHttpForLogin flag.
