### ISSUE TITLE
Could not resolve mscorlib for target framework

### ISSUE THREAD

**Issue by DavidWhitehurst** [adamdriscoll/poshprotools#231]
running windows 10
.net 4.6.1
Visual studio 2017
Installed powershell tools 
installed powershellpro tools for visual studion 2017

Create new project
Add PowershellForm
When i try to add any of the common controls i get the same error

Failed to create component 'Button'
coulc not resolve mscorlib for target framework
.NETFramwork,Version=v4.9,Profile=Client

Am i missing some other prerequisite

I tried this on my laptop as well and get the same error.

**Comment by adamdriscoll** [comment]
@DavidWhitehurst What workloads do you have installed for Visual Studio?

**Comment by DavidWhitehurst** [comment]
That was it. I had default install of vs so had no workloads installed.  Installed .net and c++ and it works as expected.
Thanks for quick response even on holiday!

**Comment by adamdriscoll** [comment]
Great! Thanks
