### ISSUE TITLE
Outgrid-Data does not support sorting

### ISSUE THREAD

**Issue by stefanstranger** [adamdriscoll/poshprotools#24]
It seems that the Outgrid-Data cmdlet does not support sorting/ordening the output.

Example:
```
$Dashboard = Start-Dashboard -Content { 
    New-Dashboard -Title "Stockprice Dashboard" -Color '#FF050F7F' -Content { 
        New-Row {
            New-Column -Size 12 {
                New-Grid -Title "StockPrice MSFT" -Headers @('Date', 'Close Stock Value') -Properties @('Date', 'close') -AutoRefresh -RefreshInterval 60 -Endpoint {
                    #Invoke-RestMethod -Uri 'https://api.iextrading.com/1.0/stock/msft/chart/6m' -Method Get | Sort-Object -property date | Out-GridData
                    (Invoke-RestMethod -Uri 'https://api.iextrading.com/1.0/stock/msft/chart/6m' -Method Get) | Select-Object @{L = 'Date'; E = {[datetime]$_.Date}}, close | 
                        Sort-Object -Property date -Descending | 
                        Select-Object @{L = 'Date'; E = {[string]$_.Date}}, close | 
                            Out-GridData
                }
            }
        }
    }
} -Port 9292

#Open Dashboard
start http://localhost:9292

#Stop Dashboard
Stop-Dashboard -Server $Dashboard
```

I want to order on date property. Showig latest stock price as first row in the table.

**Comment by adamdriscoll** [comment]
Added new parameters to New-Grid. 

- DefaultSortColumn - Specify the default column to sort by. User can still change by clicking column header.
- DefaultSortDescending - Specify the default column sort direction. User can still change by clicking column header.
 - DisableSort - Disables sort on the client and maintains whatever order was passed from the server.

**Comment by stefanstranger** [comment]
Why is DefaultSortDescending parameter of type Boolean? Shouldn't this be switch parameter?

And why is the DefaultSortColumn parameter and integer? Shouldn't this be the string name of the column?

New-Grid -Headers <string[]> -Properties <string[]> [-Title <string>] [-DisableSort] [-DefaultSortColumn <int>] [-DefaultSortDescending <bool>] [-Endpoint
 <scriptblock>] [-Id <string>] [-AutoRefresh] [-RefreshInterval <int>] [<CommonParameters>]

Currently I need to the following to have a Grid with data sorted on latest date records descending.

New-Grid -Title "StockPrice MSFT" -Headers @('Date', 'Close Stock Value') -Properties @('date', 'close') `
                    -DefaultSortColumn 0 -DefaultSortDescending 1  `
                    -AutoRefresh -RefreshInterval 60 -Endpoint {
                    $StockData = Invoke-RestMethod -Uri 'https://api.iextrading.com/1.0/stock/msft/chart/6m' -Method Get 
                    $StockData | Out-GridData 
                }

Suggestion:

New-Grid -Title "StockPrice MSFT" -Headers @('Date', 'Close Stock Value') -Properties @('date', 'close') `
                    -DefaultSortColumn 'Date' -DefaultSortDescending  `
                    -AutoRefresh -RefreshInterval 60 -Endpoint {
                    $StockData = Invoke-RestMethod -Uri 'https://api.iextrading.com/1.0/stock/msft/chart/6m' -Method Get 
                    $StockData | Out-GridData 
                }

**Comment by adamdriscoll** [comment]
@stefanstranger I like that much better. Will get that fixed today.
