### ISSUE TITLE
WinForms Filenames with Hyphen's incorrectly substitute hyphens

### ISSUE THREAD

**Issue by Atreidae** [adamdriscoll/poshprotools#240]
Seem to have found an issue where PoshTools 1.21 incorrectly substituting hyphens in filenames the Join-Path statement for the designer files.

![hyphenfilenames](https://user-images.githubusercontent.com/8736291/34454362-ecdd8cfa-edbd-11e7-824d-a0f317a9b1cb.png)

**To Replicate**
1. Create a new Project
2. Add a new item to that project
3. Select "PowerShell Form"
4. Name the new file something including a hyphen, for example "Test-ForBug.ps1" and click "Add"
5. Check the code in the new script to find the hyphen has been replaced with an underscore.

Example ". (Join-Path $PSScriptRoot 'Test_ForBug.designer.ps1')"
![replicatehyphen](https://user-images.githubusercontent.com/8736291/34454422-45e20fd2-edbf-11e7-9f6a-baf9405ece6d.png)

PoshTools Version 1.2.1
Visual Studio 2017 Community Edition Version 15.5.2

**Comment by adamdriscoll** [comment]
This will be fixed in 1.2.2.
