### ISSUE TITLE
[Login Page] - Enhancement request - Deconnection feature 

### ISSUE THREAD

**Issue by otabut** [adamdriscoll/poshprotools#242]
Hi,

It could be great to be able to disconnect after using the login page.

By the way, is there a default timeout for the opened session ? If yes, what is the default value ? can it be modified ?

Thanks.

Regards.

**Comment by adamdriscoll** [comment]
The default timeout is 25 minutes. It's a sliding expiration so the timeout starts after inactivity begins. It can't be modified at the moment but feel free to open another issue if you'd like to see that functionality.
