### ISSUE TITLE
Feature Request - Counter widget

### ISSUE THREAD

**Issue by ThePSAdmin** [adamdriscoll/poshprotools#25]
It would be nice to have a simple counter widget. I.e Just a title and a number, that can be used to show total machines running, number of users, etc. Preferably this number can be refreshed on a user specified interval.

**Comment by stefanstranger** [comment]
Maybe same feature request as my ticker widget feature request?

**Comment by adamdriscoll** [comment]
Something like this for a counter maybe? 
![image](https://user-images.githubusercontent.com/1256531/30134240-115c3060-931c-11e7-897f-e3000e60c261.png)

**Comment by stefanstranger** [comment]
@adamdriscoll yes ticker would be similar to showing a twitter timeline.

**Comment by adamdriscoll** [comment]
Coming in the next version!
