### ISSUE TITLE
Change UD background color in Endpoint

### ISSUE THREAD

**Issue by kdf2883** [adamdriscoll/poshprotools#250]
It would be awesome to be able to change the background color of a UD card from the endpoint. So if something happens where the endpoint finds a service is using too many resources or a server is down, the UD Card background color changes.

**Comment by Cragdoo** [comment]
I think this feature request already exists

https://github.com/adamdriscoll/poshprotools/issues/39

**Comment by adamdriscoll** [comment]
@kdf2883 Cragdoo is correct but in the mean time you can use a New-UDRow -Endpoint to return a New-UDCard that is customized with whatever info you want.

**Comment by adamdriscoll** [comment]
Closing as it is a duplicate.
