### ISSUE TITLE
PoshRSJob mucking with existing Charts

### ISSUE THREAD

**Issue by sgnewman** [adamdriscoll/poshprotools#257]
If I have a function which uses poshrsjob, this tends to throw monitors and other charts into a bit of a tizzy.  Specifically, they pop up with the error:

**Cannot overwrite variable PoshRS_jobCleanup because it is read-only or constant.**

![poshrsjoberror](https://user-images.githubusercontent.com/2845128/34738750-e4658776-f52e-11e7-9c56-b81837d5131c.png)

I just have this function in a scriptblock which passed to the -EndpointInitializationScript of the New-UdDashboard.

`function Get-DatabaseCounts{
        param(
            $MinCount = 1000
        )
        
        try{
            $objects = New-Object System.Collections.Generic.List[object];
            $servers | ?{$_.RoleType -in @('db0', 'db1')} | Start-RSJob -Throttle 10 -scriptblock{
                try{
                    $srv = New-Object Microsoft.SqlServer.Management.smo.Server $_.ServerName 
                    return [PSCustomObject]@{
                        ServerName = $_.DeviceName 
                        DatabaseCount = $srv.Databases.Count
                    };
                    $srv.ConnectionContext.Disconnect();
                }
                catch{

                }
            } | Wait-RSJob | Receive-RSJob | %{
                [void]$objects.Add($_);
            }
           
            return $objects | ?{$_.DatabaseCount -gt $MinCount}
        }
        catch{

        }
        finally{
            Get-RSJob | Remove-RSJob
        }
    }`
This is for both version 1.3 and exists also in version 1.4 as well.  

Let me know if you need more info.  Love this project!

**Comment by adamdriscoll** [comment]
@sgnewman This should be fixed in 1.4.0-beta3 when it's released. I was trying to overwrite readonly variables but no longer do it. When that build comes out, I'll ping you so you can try this again. 

Thanks!!

**Comment by sgnewman** [comment]
Schweet.  Let me know and I'll give it a whirl.  Not a deal-breaker, just did some caching to get over it for now...

Thanks!

**Comment by adamdriscoll** [comment]
This has been fixed and released in 1.4.1. https://www.powershellgallery.com/packages/UniversalDashboard/1.4.1
