### ISSUE TITLE
Empty UDGrid - MAX_SAFE_INTEGER is not defined

### ISSUE THREAD

**Issue by kedia990** [adamdriscoll/poshprotools#259]
I'm presented with this error message in a UDGrid component if no data was returned by the endpoint:

![image](https://user-images.githubusercontent.com/31172148/34748491-c42816c2-f56a-11e7-9ff6-7f769fcdb0ef.png)

Is that expected? I'm using UniversalDashboard 1.3.0.

Thanks!

**Comment by adamdriscoll** [comment]
Not expected! I will get this fixed for 1.4.0

**Comment by kedia990** [comment]
Thanks Adam! Appreciate your prompt responses.

**Comment by adamdriscoll** [comment]
Fixed in 1.4.0.
