### ISSUE TITLE
Feature Request - Set license cmdlet

### ISSUE THREAD

**Issue by stefanstranger** [adamdriscoll/poshprotools#26]
Currently you need to enter the license for Universal Dashboard after first launch of Dashboard in Browser. A cmdlet to have the license set would support some other scenarios, like having UD running in a Docker instance and using a Docker file which includes setting the license.

**Comment by adamdriscoll** [comment]
Implemented in my latest.

**Comment by stefanstranger** [comment]
Is it expected behavior that you need to re-configure the license after updating the UniversalDashboard Module.

Repo steps:
1. Install UniversalDashboard Module version 1.0.206
2. Run Update-Module UniversalDashboard (verson 1.0.207 is installed)
3. Create a new Dashboard.

Licence page is shown after initial Dashboard opening in Browser.

**Comment by stefanstranger** [comment]
Successfully tested Set-License and Get-License cmdlets.

But are the names for these Cmdlet not too generic? Shouldn't you add some prefix like UD to the UniversalDashboard cmdlets?

Example:
Get-UDLicense, etc.

**Comment by adamdriscoll** [comment]
@stefanstranger - The license is currently installed in module directory. Didn't really think about the upgrade scenario. I'll look into making a persistent, cross-platform way of doing that. 

Re: Naming - Yeah, I agree. I will rename to Set-UDLicense and Get-UDLicense.
