### ISSUE TITLE
New-UDChart different background color for object

### ISSUE THREAD

**Issue by skest3qc** [adamdriscoll/poshprotools#261]
Hi,
i have a simple object for BIOS Compliance:
`                            $object =@()
                            $object+= [pscustomobject]@{ Compliant = "Compliant"; Count = $Compliant.Count}
                            $object+= [pscustomobject]@{ Compliant = "NotCompliant"; Count = $NotCompliant.Count}

                            $object | Out-UDChartData -LabelProperty "Compliant" -DataProperty "Count"`

Is it possible to have a differen background color for compliant and not compliant in the chart?

Thanks

**Comment by skest3qc** [comment]
![1](https://user-images.githubusercontent.com/8022790/34825882-8fe554cc-f6d4-11e7-9638-7e0c5da932a6.png)

**Comment by skest3qc** [comment]
![1](https://user-images.githubusercontent.com/8022790/34825895-9edf9e56-f6d4-11e7-9bd2-365191c54241.png)

**Comment by Cragdoo** [comment]
Try  Out-UDChartData -LabelProperty "Compliant" -DataProperty "Count"` -BackgroundColor @("#ff0000","#02fc2c")

**Comment by skest3qc** [comment]
Thanks it works :)

I did not check that Paramter BackgroundColor takes an array of colors.

**Comment by bluearcher-bc** [comment]
I am probably just missing something obvious (it is only my first day working with UD), but is it possible to directly attach the colors to the values?  For example, I have up to 5 values, but I always want Success to be green, Fail to be red, Skipped to be Gray, etc.  It seems like this just assigns the colors by the order they are in from the source data and the order they are in the color array.

If I had 10 success and 10 fail, it would be green red, but 10 success and 10 skipped would also be green red.  Not every instance of the chart will always contain all 5 colors.
