### ISSUE TITLE
Autoreload does not work

### ISSUE THREAD

**Issue by Stephanevg** [adamdriscoll/poshprotools#268]
Hi,

I have tried the following code from the examples:

```powershell

$MyDashboard = New-UDDashboard -Title "Hello, World" -Content {
    New-UDCard -Title "Hello, Universal Dashboard" 
}

Start-UDDashboard -Port 1000 -Dashboard $MyDashboard -AutoReload

```

Simply modifying the string "Hello, Universal Dashboard"  to "Hello, Universal Woop"  and saving again doesn't refresh the output on the Dashboard.

Using ```Get-UDDashboard | stop-UDDashboard``` and re-runing the script doesn't show the updated UDCard Title either.

OS -> Windows Server 2012 R2
PS version -> 5.1

**Comment by Stephanevg** [comment]
After a few more tests, I noticed, that I actually don't need to use ```Get-UDDashboard | Stop-UDDashboard```.
If I simply close and re-open the IE window, it seems to have taken the update.

**Comment by kdf2883** [comment]
Hello Stephanevg,

You are correct. That section of code isn't needed. If you have the AutoReload Setup on the dashboard, you can leave the current webpage open and see the changes when you save the script. The webpage will refresh when the changes are made.

**Comment by Stephanevg** [comment]
Yes, this is written in the documentation [here ](https://adamdriscoll.gitbooks.io/powershell-universal-dashboard/content/command-line.html) as well.
Unfortunatley, as I explained above, saving the file isn't enough for the changes to be visible on the DashBoard. I need to re-start IE after each file change / file save I made in order to see the changes on the dashboard.

**Comment by kdf2883** [comment]
@Stephanevg Interesting I'm seeing the same issue in IE11 but not in chrome or Edge. It's probably due to the Temporary Internet Files setting in the Browser History. If you set it to **Every time I visit the webpage**  
 under the Browsing History Settings the issue goes away.
![image](https://user-images.githubusercontent.com/21251604/35105139-db0a6a46-fc38-11e7-8d19-9aa499e76185.png)
