### ISSUE TITLE
MenuStrip - adding one event causes AddRange method errors

### ISSUE THREAD

**Issue by changop** [adamdriscoll/poshprotools#269]
I've been fighting this for a while and it is holding up the next phase of a project. When adding things like the MenuStrip or ToolStrip, if I add an event action to one of them, the designer will next throw an error indicating "Method 'System.Windows.Forms.ToolStripItemCollection.AddRange' not found." It doesn't matter how many MenuStrip items I manually set up, or even if I add the control, and then right-click on the object below and Insert Standard Items, all is fine until I add one event to the strip some where.

I'm attaching the sample solution that presently has the issue, as well as recorded a quick screencast showing the behavior - https://www.screencast.com/t/M0vZMqP2NjNe

[PowerShellProject1.zip](https://github.com/adamdriscoll/poshprotools/files/1644300/PowerShellProject1.zip)

**Comment by adamdriscoll** [comment]
This should be fixed in the next build. Should be out very soon.

**Comment by changop** [comment]
Awesome, thank you for the response. I will build up the rest while waiting for the update!

**Comment by adamdriscoll** [comment]
If you update your PoshToolsPro, you should have this fixed. Thanks!
