### ISSUE TITLE
TabControl Anchor Iusses

### ISSUE THREAD

**Issue by olife373** [adamdriscoll/poshprotools#270]
Issue : Setting anchors in tab controls do not work
Temp fix : Set anchors in designer.ps1 manually

**Steps to reproduce.**
1. Start a new powershell form project.
2. Add a tab control
3. Set the anchors

Result : `$tabControl1.Anchor = ([System.Windows.Forms.AnchorStyles])`

**Comment by adamdriscoll** [comment]
This is already fixed in the source and will be available in the next build. Should be out very soon.

**Comment by adamdriscoll** [comment]
This is fixed in the latest PoshTools pro
