### ISSUE TITLE
Themes are messed up on PowerShell Core

### ISSUE THREAD

**Issue by adamdriscoll** [adamdriscoll/poshprotools#272]
![image](https://user-images.githubusercontent.com/1256531/35203973-a39a5b60-fef0-11e7-808a-78d05793b0db.png)

**Comment by artvandelay440** [comment]
I'm having this exact same thing, but on PS for Windows. I do have PSCore installed, but I'm not using that shell to invoke UniversalDashboard. Confirmed using v 1.4.1. 

The overall background and nav bars work as expected, as do UDCounters and Cards. Charts and Grids do not. This is the case for both built in themes and my custom one, across multiple dashboards.

**Comment by adamdriscoll** [comment]
I've fixed both the issue with PSCore and Charts\Grids. Will be in 1.4.2. I'll try and get that out in a week or so.
