### ISSUE TITLE
Enhancement: new-udcard -icon option

### ISSUE THREAD

**Issue by DreamThief** [adamdriscoll/poshprotools#273]
Having the -icon feature with new-udcard would be handy and allow flexibility to the function.
Similar or identical usage to new-udcounter

**Comment by adamdriscoll** [comment]
@DreamThief This is actually already there but I named it `-Watermark` for some reason. I don't know why I wasn't consistent. I think I'll change that over to `-Icon` in the 2.0 release and add an alias in the next 1.5 release.

**Comment by DreamThief** [comment]
Ah, brilliant! I see it now, thank you. The base card, however, is smaller than the watermark. I can work around this, but it is something to note. 
![image](https://user-images.githubusercontent.com/1320297/35242707-fec79e14-ff7f-11e7-8eb7-79fe17eff333.png)
The new-udcounter had this problem too, but was not as noticeable since it automatically had a second row of text.

**Comment by adamdriscoll** [comment]
Awesome. Thanks for the feedback! I added item #275 and #276.
