### ISSUE TITLE
Feature Request - Dashboard authentication 

### ISSUE THREAD

**Issue by stefanstranger** [adamdriscoll/poshprotools#29]
Authentication for accessing Universal Dashboards.

**Comment by adamdriscoll** [comment]
Implemented in the next build.

**Comment by Stephanevg** [comment]
If this is already implemented, the documentation seems not to be up to date 
here --> https://poshtools.com/2017/11/05/creating-rest-api-powershell-universal-dashboard/

**Comment by 123dev** [comment]
Hi,

Is this already integrated?
According to [this](https://adamdriscoll.gitbooks.io/powershell-universal-dashboard/content/security/rest-api-authentication.html)

I could use `Grant-UDJsonWebToken` to generate a token.
```$Token = Grant-UDJsonWebToken -UserName 'Adam'```

But I get 
```Grant-UDJsonWebToken : The term 'Grant-UDJsonWebToken' is not recognized as the name of a cmdlet```

What am I missing?

Thanks

**Comment by adamdriscoll** [comment]
Yep. You need to use UniversalDashboard rather than UniversalDashboard.Community if you want this functionality. 

```
PS C:\Users\adamr> ipmo universaldashboard
PS C:\Users\adamr> man Grant-UDJsonWebToken

NAME
    Grant-UDJsonWebToken

SYNOPSIS
    Grants a JSON web token for the specified user or application.


SYNTAX
    Grant-UDJsonWebToken -Application <String> [-Audience <String>] [-Expiry <DateTime>] [-Issuer <String>]
    [-SigningKey <String>] [-Subject <String>] [<CommonParameters>]

    Grant-UDJsonWebToken [-Audience <String>] [-Expiry <DateTime>] [-Issuer <String>] [-SigningKey <String>] [-Subject
    <String>] -UserName <String> [<CommonParameters>]


DESCRIPTION
    Grants a JSON web token for the specified user. You can adjust the JSON web token parameters in addition to
    specifying the user.


RELATED LINKS

REMARKS
    To see the examples, type: "get-help Grant-UDJsonWebToken -examples".
    For more information, type: "get-help Grant-UDJsonWebToken -detailed".
    For technical information, type: "get-help Grant-UDJsonWebToken -full".




PS C:\Users\adamr> Get-module universaldashboard

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.1.0      universaldashboard                  {Add-UDElement, Clear-UDElement, ConvertTo-JsonEx, Disable...
```

**Comment by 123dev** [comment]
Hi Adam,
Thank you for the quick response and sorry for the delay.
Moved to UniversalDashboard  and it's working fine.

Much appreciated the assistance. :)
Thanks
