### ISSUE TITLE
New-Table Does Not Refresh & Drops Data

### ISSUE THREAD

**Issue by Rick-2CA** [adamdriscoll/poshprotools#33]
When performing an auto refresh with New-Table the last row of the table is dropped and the data isn't refreshed.  This can be reproduced by adding `-AutoRefresh -RefreshInterval 10` to the Server Information table in server-performance-dashboard.ps1.  I added a table entry that uses `Get-Date` to show that the data wasn't being refreshed in my test.

**Comment by adamdriscoll** [comment]
Fixed in the next build.
