### ISSUE TITLE
New-Grid Width

### ISSUE THREAD

**Issue by Rick-2CA** [adamdriscoll/poshprotools#34]
The data width of New-Grid can surpass the border New-Column.  Depending on the data content it'll take up more space than allotted.  Using the example's `Get-Process` I had to set the size to a low number to reproduce the behavior.  Using my data, which includes a few properties with long strings, even a size of 12 wasn't enough without cutting down some properties.

I think a perfect world would give me a grid with horizontal scrolling if it were to surpass the column size set.

**Comment by adamdriscoll** [comment]
Next build will do this. 

![image](https://user-images.githubusercontent.com/1256531/30454344-95ec31c2-9961-11e7-8d47-7a41fd06df04.png)
