### ISSUE TITLE
Stop-Dashboard Clarity

### ISSUE THREAD

**Issue by Rick-2CA** [adamdriscoll/poshprotools#35]
This is a first world issue, but I had trouble understanding the use of Stop-Dashboard.  It requires you to be explicit in calling the cmdlet.  I expected to be able to do `Stop-Dashboard $Dashboard` instead of `Stop-Dashboard -Server $Dashboard`.  I also expected to be able to provide a value for `Server` in the form of the server name.  There's no code method of stopping a dashboard if you didn't save `Start-Dashboard` to a variable.  The already requested `Get-Dashboard` should empower that action though.

**Comment by adamdriscoll** [comment]
Implemented in https://github.com/adamdriscoll/poshprotools/releases/tag/ud-1.0.210

Fixed the Stop-Dashboard parameters to be positional. 

This works.

`Stop-Dashboard $Server`

Dashboards now have names. 

```
Start-Dashboard -Name "My Super Sweet Dashboard" ...
Stop-Dashboard -Name "My Super Sweet Dashboard"
```

Also added Get-Dashboard. 

`Get-Dashboard | Stop-Dashboard`
