### ISSUE TITLE
Functions within widgets

### ISSUE THREAD

**Issue by osh20** [adamdriscoll/poshprotools#38]
The dashboard does not recognise custom functions that are declared outside of the 'start-dashboard'.

**Comment by adamdriscoll** [comment]
@osh20 Currently, a new runspace is created within the ASP.NET web service. You would need to create a module and import it in the Endpoint parameter of widgets. 

I'll look at making this work seamlessly.

**Comment by adamdriscoll** [comment]
I would like to propose a Initialization script block. This script block would be defined at the dashboard level. The script block itself would be called within any runspace within UD. Here's how I envision the API looking. 

```
$Initialization = {
     $SomeVariableIWantEverywhere = "This is a variable" 
     function SomeFunctionXyz {

     }
}

New-UDDashboard -InitializationScriptBlock $Initialization
```

Internally, in the runspace, I could call the initialization code whenever a new runspace is created. Runspaces are currently created during heavy load. If there is a runspace available for a request that isn't being used, it will be used but if not, a new runspace will be created. Once a runspace is returned to the pool it will either be discarded or cached for future requests.

**Comment by mattmcnabb** [comment]
+1 on the -InitializationScript parameter. This is consistent with how a job would import a module. The benefit would be that we could either import a module in the script, or define custom functions there as well.

**Comment by osh20** [comment]
+1. Another benefit is to clean code without redundant import-modules, or declaring variables.

**Comment by adamdriscoll** [comment]
This will be available in the next version
