### ISSUE TITLE
Error MSB3644 when packaging executable

### ISSUE THREAD

**Issue by i3igi3yrd** [adamdriscoll/poshprotools#46]
When trying to package a ps1 as an executable, I'm getting the following error. This is on all Powershell Script projects and all computers. All .net framework installed.:

Build FAILED.

C:\Program Files\dotnet\sdk\1.1.0\Microsoft.Common.CurrentVersion.targets(1122,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [C:\Users\johnb\AppData\Local\Temp\fdbac9b1bba9475bbc647f7d1cb54b2f\Form1.csproj]
    0 Warning(s)
    1 Error(s)

**Comment by adamdriscoll** [comment]
Could you please try installing the .NET 4.6.2 developer pack? https://www.microsoft.com/en-us/download/details.aspx?id=53321

I need to fix this so you can select the .NET framework rather than defaulting to 4.6.2.

**Comment by i3igi3yrd** [comment]
I came back to say I found that solution. Thanks.

**Comment by adamdriscoll** [comment]
Cool. I'm using #5 to track the enhancement to this.
