### ISSUE TITLE
Adding PictureBox

### ISSUE THREAD

**Issue by i3igi3yrd** [adamdriscoll/poshprotools#48]
When selecting an image for PictureBox, I get the error:

Error invoking 'Choose Image...'. Details:
Value cannot be null.
Parameter name: docData

This is happening on multiple machines.

**Comment by i3igi3yrd** [comment]
Update: saw the bug. 
Somehow missed it before posting.

**Comment by adamdriscoll** [comment]
@i3igi3yrd Yep. Duplicate of #19

**Comment by adamdriscoll** [comment]
@i3igi3yrd This is implemented in the next version and will be out in the next couple days.
