### ISSUE TITLE
Hiding Console Window

### ISSUE THREAD

**Issue by i3igi3yrd** [adamdriscoll/poshprotools#49]
Whenever I go to the properties for the project and select Hide Console Window (along with the other selections on this screen) all but this option stays checked. 

I've not been able to actually get it to successfully package without showing the console window. Am I missing something?

**Comment by adamdriscoll** [comment]
Sounds like a bug. I will take a look.

**Comment by adamdriscoll** [comment]
This has been fixed in the most recent version.
