### ISSUE TITLE
UniversalDashboard install failing due to already existing command (New-Link)

### ISSUE THREAD

**Issue by Windos** [adamdriscoll/poshprotools#54]
I've installed UniversalDashboard at work and now at home, and both times the install has failed with a complaint that New-Link is already available. I can't actually find any modules with that as an exported commands.

Re-running the install with the `-AllowClobber` switch works, but given this error only comes up after the install and the Gallery is pretty slow (even on gigabit fibre) it's means sitting and waiting for a few minutes twice.

![Screenshot](https://user-images.githubusercontent.com/6955786/31266400-2209c3b6-aad0-11e7-8e79-576705f53e88.png)

Both machines are Windows 10, builds 10.0.15063.632 & 10.0.16299.15.

**Comment by adamdriscoll** [comment]
Hmmm. I've thought about this a bit and I really think that the module should have prefixed commands:

New-UDLink
New-UDCard 
New-UDDashboard

I know it would break existing implementations but I think it's something that needs to be done to avoid this.

**Comment by adamdriscoll** [comment]
Fixed in next version. All cmdlets will be prefixed with UD.
