### ISSUE TITLE
Issues after creating a form in Designer View

### ISSUE THREAD

**Issue by Ruckster** [adamdriscoll/poshprotools#55]
I've just installed PowerShell Pro and Tools onto Visual Studio 2017 Community.  When I create a PowerShell form in Designer, save and close the form, when I try and reopen the file with Designer it will not open the form and then shows multiple errors.

Below are a few of the errors it reports:

At line:84 char:37 + $tableLayoutPanel1.ColumnStyles.Add(New-Object -TypeName  System.Windo ... + ~ Missing ')' in method call. At line:84 char:37 +  $tableLayoutPanel1.ColumnStyles.Add(New-Object -TypeName System.Windo ... +  ~~~~~~~~~~ Unexpected token 'New-Object' in expression or statement. At line:38  char:1 + { + ~ Missing closing '}' in statement block or type definition. At  line:84 char:151 + ... mnStyle -ArgumentList  @([System.Windows.Forms.SizeType]::Percent,50)) + ~ Unexpected token ')' in  expression or statement. At line:91 char:34 +  $tableLayoutPanel1.RowStyles.Add(New-Object -TypeName System.Windows. ... + ~  Missing ')' in method call. At line:91 char:34 +  $tableLayoutPanel1.RowStyles.Add(New-Object -TypeName System.Windows. ... +  ~~~~~~~~~~ Unexpected token 'New-Object' in expression or statement. At line:91  char:151 + ... e -ArgumentList  @([System.Windows.Forms.SizeType]::Percent,8.649468)) + ~ Unexpected token ')'  in expression or statement. At line:92 char:34 +  $tableLayoutPanel1.RowStyles.Add(New-Object -TypeName System.Windows. ... + ~  Missing ')' in method call. At line:92 char:34 +  $tableLayoutPanel1.RowStyles.Add(New-Object -TypeName System.Windows. ... +  ~~~~~~~~~~ Unexpected token 'New-Object' in expression or statement. At line:92  char:151 + ... e -ArgumentList  @([System.Windows.Forms.SizeType]::Percent,91.35053)) + ~ Unexpected token ')'  in expression or statement. Not all parse errors were reported. Correct the  reported errors and try again. | At line:84 char:37 + $tableLayoutPanel1.ColumnStyles.Add(New-Object -TypeName  System.Windo ... + ~ Missing ')' in method call. At line:84 char:37 +  $tableLayoutPanel1.ColumnStyles.Add(New-Object -TypeName System.Windo ... +  ~~~~~~~~~~ Unexpected token 'New-Object' in expression or statement. At line:38  char:1 + { + ~ Missing closing '}' in statement block or type definition. At  line:84 char:151 + ... mnStyle -ArgumentList  @([System.Windows.Forms.SizeType]::Percent,50)) + ~ Unexpected token ')' in  expression or statement. At line:91 char:34 +  $tableLayoutPanel1.RowStyles.Add(New-Object -TypeName System.Windows. ... + ~  Missing ')' in method call. At line:91 char:34 +  $tableLayoutPanel1.RowStyles.Add(New-Object -TypeName System.Windows. ... +  ~~~~~~~~~~ Unexpected token 'New-Object' in expression or statement. At line:91  char:151 + ... e -ArgumentList  @([System.Windows.Forms.SizeType]::Percent,8.649468)) + ~ Unexpected token ')'  in expression or statement. At line:92 char:34 +  $tableLayoutPanel1.RowStyles.Add(New-Object -TypeName System.Windows. ... + ~  Missing ')' in method call. At line:92 char:34 +  $tableLayoutPanel1.RowStyles.Add(New-Object -TypeName System.Windows. ... +  ~~~~~~~~~~ Unexpected token 'New-Object' in expression or statement. At line:92  char:151 + ... e -ArgumentList  @([System.Windows.Forms.SizeType]::Percent,91.35053)) + ~ Unexpected token ')'  in expression or statement. Not all parse errors were reported. Correct the  reported errors and try again.
-- | --
At line:84 char:37 + $tableLayoutPanel1.ColumnStyles.Add(New-Object -TypeName  System.Windo ... + ~ Missing ')' in method call. At line:84 char:37 +  $tableLayoutPanel1.ColumnStyles.Add(New-Object -TypeName System.Windo ... +  ~~~~~~~~~~ Unexpected token 'New-Object' in expression or statement. At line:38  char:1 + { + ~ Missing closing '}' in statement block or type definition. At  line:84 char:151 + ... mnStyle -ArgumentList  @([System.Windows.Forms.SizeType]::Percent,50)) + ~ Unexpected token ')' in  expression or statement. At line:91 char:34 +  $tableLayoutPanel1.RowStyles.Add(New-Object -TypeName System.Windows. ... + ~  Missing ')' in method call. At line:91 char:34 +  $tableLayoutPanel1.RowStyles.Add(New-Object -TypeName System.Windows. ... +  ~~~~~~~~~~ Unexpected token 'New-Object' in expression or statement. At line:91  char:151 + ... e -ArgumentList  @([System.Windows.Forms.SizeType]::Percent,8.649468)) + ~ Unexpected token ')'  in expression or statement. At line:92 char:34 +  $tableLayoutPanel1.RowStyles.Add(New-Object -TypeName System.Windows. ... + ~  Missing ')' in method call. At line:92 char:34 +  $tableLayoutPanel1.RowStyles.Add(New-Object -TypeName System.Windows. ... +  ~~~~~~~~~~ Unexpected token 'New-Object' in expression or statement. At line:92  char:151 + ... e -ArgumentList  @([System.Windows.Forms.SizeType]::Percent,91.35053)) + ~ Unexpected token ')'  in expression or statement. Not all parse errors were reported. Correct the  reported errors and try again.

When I open the code of the  designer.ps1 file, all of the lines that references "New-Object" has "Unexpected token 'New-Object' in expression or statement".

If I add an additional "()" around the already (New-Object......) then that error goes away.  However, then when I try to view with designer again I get the following:

Method 'System.Windows.Forms.TableLayoutColumnStyleCollection.Add' not found. | Method 'System.Windows.Forms.TableLayoutColumnStyleCollection.Add' not found.
-- | --
Method 'System.Windows.Forms.TableLayoutColumnStyleCollection.Add' not found.

So I still can't get a designer view again.

If anyone has experienced this and knows of a solution, I would appreciate the help.  I've spent a lot of hours trying to troubleshoot and solve this unsuccessfully.  Thanks

**Comment by adamdriscoll** [comment]
@Ruckster Could you upload the project so I could take a look? If you can't upload publicly, you can email me at adam[at]poshtools.com.
