### ISSUE TITLE
Provide some way to pause page cycling

### ISSUE THREAD

**Issue by adamdriscoll** [adamdriscoll/poshprotools#59]

**Comment by Windos** [comment]
If I could be cheeky and suggest a possible UX to take inspiration from, I'm a fan of how [Pulseway](https://www.pulseway.com) does their dashboard controls:

![dashux-1](https://user-images.githubusercontent.com/6955786/31566596-d0d81224-b0c7-11e7-812c-6b5c01e8f873.png)

![dashux-2](https://user-images.githubusercontent.com/6955786/31566597-d43d4236-b0c7-11e7-8deb-b06ca5708b9e.png)

**Comment by adamdriscoll** [comment]
Implemented in next build.
