### ISSUE TITLE
ChartJS Options do not appear to work.

### ISSUE THREAD

**Issue by adamdriscoll** [adamdriscoll/poshprotools#62]
I’m trying to force the graph to start with 0, but using `-Options @{ scales = @{ yAxes = @( @{ ticks = @{ beginAtZero = $true }  } ) } }` does not worked. From the docs it should be just, maybe I’m just missing something?

```
options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
```

**Comment by gpduck** [comment]
New-UDChart is serializing the options to a json string and then the dashboard controller serializes the string again and the render* functions on the client are expecting it to have already been parsed.

**Comment by adamdriscoll** [comment]
@gpduck Thanks, Mr. Duck! I'll get this fixed.

**Comment by adamdriscoll** [comment]
Fixed in the next build.
