### ISSUE TITLE
New-UDChart doesn't show anything when a count of 1 is returned

### ISSUE THREAD

**Issue by adamdriscoll** [adamdriscoll/poshprotools#65]
Count = 1 does not show anything, but if more than 1, it shows the data. I have the following 
Get-MsolUser | Group-Object -Property UsageLocation | Select Count, Name | Out-UDChartData -DataProperty "Count" -LabelProperty "Name"

**Comment by artvandelay440** [comment]
As a workaround, I've seen this and used `($ListWithOneObject | Measure-Object).count` 
It seems piping to Measure-Object first fixes it. Hope that helps!
