### ISSUE TITLE
Error during autoreload

### ISSUE THREAD

**Issue by adamdriscoll** [adamdriscoll/poshprotools#70]
> Exception setting "CursorPosition": "A command that prompts the user failed because the
> host program or the command type does not support user interaction. Try a host program t
> hat supports user interaction, such as the Windows PowerShell Console or Windows PowerSh
> ell ISE, and remove prompt-related commands from command types that do not support user
> interaction, such as Windows PowerShell workflows."
> Cannot convert argument "fill", with value: "System.Collections.Hashtable", for "SetBuff
> erContents" to type "System.Management.Automation.Host.BufferCell": "Cannot create objec
> t of type "System.Management.Automation.Host.BufferCell". Cannot convert null to type "S
> ystem.ConsoleColor" due to enumeration values that are not valid. Specify one of the fol
> lowing enumeration values and try again. The possible enumeration values are "Black,Dark
> Blue,DarkGreen,DarkCyan,DarkRed,DarkMagenta,DarkYellow,Gray,DarkGray,Blue,Green,Cyan,Red
> ,Magenta,Yellow,White"."
> Transcription cannot be started.
> An error occurred stopping transcription: The host is not currently transcribing.
>

**Comment by quickware** [comment]
I had the exact same error. It occurs when I run a powershell script on remote servers and the script has 
>cls 
command in it. 
So removing the cls command from sub-srcipts resolved the exception.
