### ISSUE TITLE
New-Chart Type Pie not valid

### ISSUE THREAD

**Issue by Cragdoo** [adamdriscoll/poshprotools#79]
Documentation lists options as 

> Charts can be either bar, line, doughnut or pie

but setting New-Chart -Type Pie throws up errors

> Cannot bind parameter 'Type'. Cannot convert value "Pie" to type "PowerShellProTools.UniversalDashboard.Models.ChartType". Error: "Unable to match the identifier name Pie to a valid enumerator name. Specify one of the
 following enumerator names and try again:
Bar, Line, Area, Doughnut"
Cannot bind argument to parameter 'Dashboard' because it is null.

**Comment by adamdriscoll** [comment]
Fixed in next build.
