### ISSUE TITLE
Suggestion: PoshUD Easy REST API 

### ISSUE THREAD

**Issue by JohnLBevan** [adamdriscoll/poshprotools#84]
Posh UD looks amazing; thank-you.

Something else which would be helpful would be a way to generate web services as easily as your solution generates dashboards; i.e. so that we can use PS scripts to quickly run up REST or OData services, which can then be consumed by other scripts or tools.

I recognise that this is out os scope of PoshUD itself; but maybe a PoshRest solution could be knocked up reusing much of the logic used already to present PoshUD?

**Comment by adamdriscoll** [comment]
I like it!

**Comment by adamdriscoll** [comment]
Implemented in next build.
