### ISSUE TITLE
All Examples include @colors splat, but this is only defined on first example

### ISSUE THREAD

**Issue by 1RedOne** [adamdriscoll/poshprotools#90]
All examples on the [Components page ](http://www.poshud.com/Components) reference the `$colors` variable, but this is only defined on the main page.  Here is an example from that page:

````New-UDChart -Title "Feature by operating system" -Type Bar -AutoRefresh -RefreshInterval 7 @Colors -Endpoint````

Note the splat of @Colors there.

The average user (like me) will copy components from the example page and try pasting them in to a blank DashBoard and get this error

````
New-UDChart : A positional parameter cannot be found that accepts argument '$null'.
At line:1 char:12
+ $content = New-UDChart -Title "Feature by operating system (Area)" -T ...
````

If @Colors were defined on each example, this error would be mitigated.  OR, @Colors could provide a default coloring rule and then remove the `@colors` from the examples.

**Comment by adamdriscoll** [comment]
Fixed
