### ISSUE TITLE
UniversalDashboard method not found

### ISSUE THREAD

**Issue by sheldonhull** [adamdriscoll/poshprotools#99]
https://github.com/adamdriscoll/poshtools/issues/574

I accidentally put this in the wrong place. 
Unable to get UD to run with any of my test endpoint scripts. Any ideas?

**Comment by adamdriscoll** [comment]
@sheldonhull Oh that's not good. Can you please provide $PSVersionTable for me? Do you have multiple versions of the module installed?

**Comment by sheldonhull** [comment]
5.1 
I have uninstalled all versions and reinstalled only the current and get this message

**Comment by sheldonhull** [comment]
I went back and doublechecked again, and found more versions I swear I removed lol. Uninstalled for SURE all other versions. Now running `1.0.271`

Running the example in the code repo of 
```
Start-UDDashboard -Content { 
    New-UDDashboard -Title "Server Performance Dashboard" -Color '#FF050F7F' -Content { 
        New-UDTable -Title "Server Information" -Headers @("Name", "CommandLine", "Status") -Endpoint {
              Get-Service | Select Name,CommandLine,Status | Out-UDTableData -Property @("Name", "CommandLine", "Status")
          }
      }
 } -Port 1001
```
I get the error: `Method not found: 'Void NLog.Logger.Error(System.Exception, System.String)'.`

Note that I enabled UDlogging and no error details in there at all

**Comment by adamdriscoll** [comment]
@sheldonhull Can you try running this? 

`(Get-Item ([APpDOmain]::CurrentDomain.GetAssemblies() | Where Location -Like "*NLog*" ).Location).VersionInfo`

**Comment by sheldonhull** [comment]
This is what was returned

```
ProductVersion   FileVersion      FileName                                                                                                                                                                
--------------   -----------      --------                                                                                                                                                                
4.2.3            4.2.3.1371       C:\Users\ME\Documents\WindowsPowerShell\Modules\PsISEProjectExplorer\1.4.0\NLog.dll
```

I still use ISEProjectExplorer when using ISE (trying to transition to vscode but struggling with various pieces working as expected). 

I'll try unload ISEProjectExplorer and see if behavior changes

**Comment by sheldonhull** [comment]
Ok, once I removed ISEProjectExplorer the project worked correctly lol. Could you wrap up this dll reference to explicitly define your nlog dll load? 

Excited as I *finally* get to play around with this posh magic :-)

**Comment by adamdriscoll** [comment]
Ah great. Thanks!
